### ISSUE TITLE
Отслеживание новых тем.

### ISSUE THREAD

**Issue by p12se** [ElizarovEugene/TorrentMonitor#103]
Очень хорошо если бы была возможность, которая позволяла отслеживать новые темы на трекере. 
Когда выходят новые темы с фильмами, например тема называется **Трансформеры: Эпоха истребления / Transformers: Age of Extinction (2014) BDRip 1080p | iTunes Russia** из названия видно, что фильм в харошем качасте **BDRip** и переводе **iTunes Russia**, а значит я хочу, что бы скачался такой фильм.
Все эти параметры лучше задавать через _настройки_, что бы не было хлама и не качалось все подряд можно сделать, что бы была возможность  подтверждение перед скачиванием. Если спустя время не было _одобрения_ на скачивание, то такие темы удалялись.

**Comment by cisco2** [comment]
Как это делается во flexget:
Для flexget-овского плугина regexp настраиваются ключи accept и regect. Для примера ТС выше accept будет "Transformers: Age of Extinction". Для этого же примера regect будет
        - 'Blu-ray'
        - 'Blu-Ray'
        - 'BD-Remux'
        - 'BDRemux'
        - '1080i'
#        - '1080p'
        - '720p'
        - 'HD720p'
#        - 'BDRip'
        - 'WEB-DL'
        - 'HDTVRip'
        - 'HDTV '
        - 'WEBDLRip'
        - 'WEB-DLRip'
        - 'XviD'
        - 'DVDRip'
#        - 'iTunes Russia'
Заремленные строки - это #. Т.е. regect все, что незаремлено.
Итого получим на выходе раздачу, содержащую в названии "Transformers: Age of Extinction BDRip 1080p iTunes Russia" и не содержащую в названии все вышеуказанные незаремленные ключи. 
Ключи regect, конечно нужно вводить самому исходя из правил оформления раздач на трекере. И для разных трекеров они будут разными. Например сериал "Сотня" где-то пишут "The 100", где-то "The Hundred" :-) Но все это работает достаточно надежно, хотя бывают, конечно, и ошибки - в основном по раздачам, оформленным с нарушениями правил трекера или раздачам - почти повторам.

**Comment by ElizarovEugene** [comment]
>нужно вводить самому исходя из правил оформления раздач на трекере
о чём собственно я и говорил. а учитывая то, что я стараюсь пользователей оградить от этого и всё реализовать менюшками настроек, а не вводом параметров вручную - это выглядит очень геморно

**Comment by diaskooo** [comment]
https://github.com/jzjzjzj/parse-torrent-name правда nodejs

конечно работает не на все 100% но регулярки можно подрпавить

Трансформеры: Эпоха истребления / Transformers: Age of Extinction (2014) BDRip 1080p | iTunes Russi

{ year: 2014,
  resolution: '1080p',
  title: 'Трансформеры: Эпоха истребления / Transformers: Age of Extinction',
  group: 'Russi',
  excess: [ 'BDRip', '|', 'iTunes' ] }

Трансформеры: Эпоха истребления 2D, 3D / Transformers: Age of Extinction 2D, 3D (2014) BDRemux 1080р от ExKinoRay | 3D-Video | IMAX | iTunes Russia

{ year: 2014,
  episodeName: 'Video | IMAX | iTunes Russia',
  title: 'Трансформеры: Эпоха истребления 2D, 3D / Transformers: Age of Extincti
on 2D, 3D',
  excess: [ 'BDRemux', '1080р', 'от', 'ExKinoRay', '|', '3D' ] }

Эпоха истребления / Transformers: Age of Extinction (2014) HDRip от Scarabey | IMAX | Чистый звук

{ year: 2014,
  quality: 'HDRip',
  title: 'Эпоха истребления / Transformers: Age of Extinction',
  group: 'звук',
  excess: [ 'от', 'Scarabey', '|', 'IMAX', '|', 'Чистый' ] }

Трансформеры: Эпоха истребления / Transformers: Age of Extinction (Майкл Бэй / Michael Bay) [2014, США, Китай, фантастика, боевик, приключения, BDRip] [IMAX] Dub iTunes + Sub rus forced

{ year: 2014,
  title: 'Трансформеры: Эпоха истребления / Transformers: Age of Extinction',
  group: 'forced',
  excess:
   [ 'Майкл',
     'Бэй',
     'Michael',
     'Bay',
     ',',
     'США,',
     'Китай,',
     'фантастика,',
     'боевик,',
     'приключения,',
     'BDRip]',
     '[IMAX]',
     'Dub',
     'iTunes',
     '+',
     'Sub',
     'rus' ] }
