### ISSUE TITLE
Версия 1.1

### ISSUE THREAD

**Issue by ElizarovEugene** [ElizarovEugene/TorrentMonitor#115]
И так, версию 1.1 я мучал очень долго ввиду огромной занятости, писал её с большими перерывами, по этому могут быть баги и косяки. Выложил пока сюда, перед тем как сделать официальный апдейт через сам ТМ (там ещё update.php надо для этого поправить). Обо всех багах прошу писать сюда. Надеюсь обновление многих порадует, сделано многое из того что просили.

**Comment by alegzz** [comment]
так  и не исправили функции, которые работают со строками, на многобайтовые. соответственно на более-менее свежих версиях php парсить юникодные даты с кириллицей будет криво

**Comment by ElizarovEugene** [comment]
@alegzz вы снова про mb_substr?
не знаю что там в свежих версиях php - пока ещё жалоб небыло, могу сказать про себя: 
$str="проверка";
echo mb_substr($str, 0, 3); #п�
echo substr($str, 0, 6); #про

PHP 5.4.*
у вас что то не работает на какой то другой версии?

**Comment by alegzz** [comment]
так ведь в исходниках не так:
nnm-club
	$month = mb_substr($data, 3, 6);

**Comment by ElizarovEugene** [comment]
Ну это значит я в файле nnm-club накосячил в своё время, во всех остальных substr используется
очень интересно почему mb_substr на разных версиях ведёт себя по разному и на "старых" по суди работает не верно

**Comment by cisco2** [comment]
Обновился до 1.1 Добавляю тему http://nnm-club.me/forum/viewtopic.php?t=868157 
Жму "Запуск". В веб интерфейсе дата последнего обновления появляется. На вкладке "Ошибки" вижу 
12 Фев 2015 14:54 	  Transmission 	  Не удалось получить данные torrent-файла.
В /var/www/html/htdocs/torrentmonitor/torrents торрент-файл лежит, в трансмишен-демон раздача не добавилась.

**Comment by ElizarovEugene** [comment]
@cisco2 а ты не проверял - торрент-файл скачался валидный? у меня скачался без проблем верный, в клиент не добавился - у меня тут инфраструктурный переезд на новое оборудование полным ходом, сейчас у ТМ нет доступа к клиенту

**Comment by cisco2** [comment]
Нормальный. Скачал его с HTPC (там и трансмишен-демон и торрент-монитор), добавил вручную - перехэшировалось ОК, в профиле на трекере раздача появилась.
На casstudio.tv ситуация аналогичная. Торрент-файл скачался, в базу хэш не записан, в трансм-демон не добавился, вручную торрент-файл добавился нормально.

**Comment by kea255** [comment]
В update.mysql.sql ошибки.
DELETE * FROM - звездочку надо убрать
DELETE FROM `warning` WHERE `tracker` = 'lostfilm.tv'; - в warning нет колонки tracker
---
 И торрент файл всегда сохраняеться в torrentmonitor\torrents\ не смотря на настройки

**Comment by cisco2** [comment]
kea255, где же ты раньше был... Наткнулся на эти ошибки, не стал разбираться и накатил mysql.sql из db_schema... А он всю базу потер... Благо там и было то всего ничего записей...

**Comment by kea255** [comment]
Сейчас в Transmission передаеться команда по RPC. И это здорово, раньше я каждый раз прописывал полный путь к /usr/local/bin/transmission-remote, сюда лень писать было. Сейчас это нафиг не надо. Торрент файл всегда сохраняеться в папке torrents.
В настройках нотификации прописал свой Email и полный URL к TorrentMonitor. и все работает.

**Comment by cisco2** [comment]
kea255, а как из ТМ передавать закачки в rtorrent например ?

**Comment by kea255** [comment]
rtorrent следить за какойто папкой так? либо прописать туда папку ТутПутьКТоррентМонитор\torrents\
Или сделать симлинк ln -s ТутПутьКТоррентМонитор\torrents\ ТутПутьКудаСмотритРторент

**Comment by kea255** [comment]
Ну или вот версия 1.0.4 с фиксом nnm-club.ws http://master.ulspu.ru/torrentmonitor/torrentmonitor1.0.4upd.zip

**Comment by cisco2** [comment]
Про симлинки я в курсе :-) Средствами ТМ-а как передать ? Я веду к тому, что логично было бы "если стоит галка 'управлять торрент-клиентом' то поле ввода пути сохранения торрент-файла отсутствует. Вместо него выбор клиента+ввод IP/порт/login/parol. Если галки нет, то появляется поле, куда нужно ввести этот путь". ИМХО

**Comment by cisco2** [comment]
Надо делать фак или вики. Если не участвовать в процессе добавления какого-то функционала, то потом хрен поймешь например что значит (на что влияет) поле "Адрес TorrentMonitor" и что туда писАть. Сейчас вбил туда свой домашний ip-шник и ломаю голову - а правильно ли это и где аукнется ?
Готов ( посильно ) помогать.

**Comment by kea255** [comment]
Посмотрел по коду. В вашем случае ни на что не влияет. Нужно для нового метода добавления торрент фалов в Transmission и Deluge

**Comment by ElizarovEugene** [comment]
Господа, не торопитесь - описание что для чего нужно - появится в блоге, как только я выкачку "официально" 1.1
@cisco2 если файл сохранился верный, значит проблема с передачей в ТМ, можно включить в файле Transmission.class debug и в меня его данными кинуть
Адрес TorrentMonitor - просто его http арес, что бы формировать ссылки для RSS и передачи клиентам
Удалять раздачи - просто переименовано, удаляет из клиента - всегда, а файлы только для lostfilm.tv, novafilm.tv, baibako.tv и newstudio.tv
"а как из ТМ передавать закачки в rtorrent, qbittorrent и т.д. например" а как ты их раньше передавал? директория захардкорена не только из-за клиентов, но из-за рсс ленты
"Может надо было вместо 192.168.1.39 вбить 127.0.0.1 или доменное имя" ну лупбэк не надо, а доменное имя можно, у меня так и сделано

но вообще если кто то возьмётся писать описание - буду рад, я его запихаю прям в хэлп, пока он у меня достаточно куций получился

**Comment by cisco2** [comment]
Евгений, отправил выхлоп debug на почту

**Comment by cisco2** [comment]
Я чувствовал, что дело именно в этом....
@ElizarovEugene , на странице "Настройка" нужно заменить формулировку "Адрес TorrentMonitor" на "URL адрес вашего TorrentMonitor" или что-то подобное. Проблема была (кроме слэша по дебаг логу) еще и в этом. Фразу "Адрес TorrentMonitor" я понял как "IP/доменный  Адрес TorrentMonitor", а подразумевается "url/http адрес доступа к TorrentMonitor". Т.е. у меня в этом поле стояло "192.168.1.39", а нужно было "http://192.168.1.39/htdocs/torrentmonitor/". Вроде не дурак и на одном языке говорим, ан во как получается....

**Comment by ElizarovEugene** [comment]
@cisco2 а моего описания параметра в хелпе не достаточно?

**Comment by vlmaksime** [comment]
Ведь PHP умеет получать текущее значение из адресной строки?
Может рядом с этим полем сделать кнопку "Установить текущее значение", которая будет брать адрес ную строку, обрезать у нее в конце "#" и подставлять в эту строку.

**Comment by cisco2** [comment]
@ElizarovEugene , этого хелпа ?
http://s1.hostingkartinok.com/uploads/images/2015/02/3dd75ddbed48e7c698199d65f3dd30d0.png
Если это он, то явно недостаточно.
@vlmaksime - посмотри на мою адресную строку. ТМ работает в домашней сети на HTPC (url в домашней сети на него приводил выше), в интернет HTPC смотрит только по ssh. В рабочее время к нему попадаю из инета через туннели поверх ssh - поэтому урл становится совсем другим.

**Comment by ElizarovEugene** [comment]
@cisco2 я буквально вчера-позавчера доливал новую версию хелпа и расписал там про все настройки

**Comment by vlmaksime** [comment]
@cisco2 дело не в том, какой url видите Вы при подключении. В это поле надо указывать url, который будет виден из подсети, в которую установлен торрент-клиент. Думаю, что после ознакомления с обновленным хелпом все Ваши вопросы должны будут уйти.
