### ISSUE TITLE
302 на https nnm-club.ws

### ISSUE THREAD

**Issue by kea255** [ElizarovEugene/TorrentMonitor#119]
Некоторые торрент файлы на nnm-club.me редиректятся на https://nnm-club.ws
При этом CURLOPT_FOLLOWLOCATION ведет себя неадекватно. Нашел подобный баг на багтрекере вордпресса (https://core.trac.wordpress.org/ticket/17490)

Для себя временно исправил так:
System.class.php
```
140a141,144
>
>                       curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
>
>                       $result = curl_exec($ch);
142c146,157
<               $result = curl_exec($ch);
---
>                       if (in_array(curl_getinfo($ch,CURLINFO_HTTP_CODE), array( 301, 302)) && $param['type'] == 'POST'){
>                               $url = curl_getinfo($ch,CURLINFO_EFFECTIVE_URL);
>                               curl_close($ch);
>                               $ch = curl_init($url);
>                               curl_setopt ($ch, CURLOPT_USERAGENT, 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.0.3) Gecko/2008092417 Firefox/3.0.3');
>                               curl_setopt ($ch, CURLOPT_RETURNTRANSFER, 1);
>                               curl_setopt ($ch, CURLOPT_SSL_VERIFYPEER, 0);
>                               curl_setopt ($ch, CURLOPT_SSL_VERIFYHOST, 0);
>                               curl_setopt($ch, CURLOPT_VERBOSE, true);
>                               $result = curl_exec($ch);
>                       }
```

**Comment by ElizarovEugene** [comment]
У вас последняя версия системы и файла nnm-club.engine?

**Comment by kea255** [comment]
Только сейчас понял что нет. TorrentMonitor v. 1.0.4 Автообновления чтото не сработало.
Там это как-то подругому исправлено?

**Comment by kea255** [comment]
Все вижу, в 1.1 исправлено, идет сразу запрос на nnm-club.ws
Вот только в changlog и http://korphome.ru/torrent_monitor/version.xml последняя версия указана 1.0.4

**Comment by ElizarovEugene** [comment]
Но вот вы новую темы создали, а дямо как раз моя тема где всё написано
https://github.com/ElizarovEugene/TorrentMonitor/issues/115

**Comment by cisco2** [comment]
Аналогично с TorrentMonitor v. 1.0.4 Автообновления чтото не сработало.
