### ISSUE TITLE
Предлагаю/прошу сделать запуск внешнего скрипта при обновлении раздачи

### ISSUE THREAD

**Issue by cisco2** [ElizarovEugene/TorrentMonitor#120]
Предлагаю/прошу сделать запуск внешнего скрипта при обнаружении ТМ-ом перезаливки раздачи для трекеров с обновляемыми релизами (а для lostfilm.tv, novafilm.tv, baibako.tv и newstudio.tv - соответственно при нахождения искомой раздачи ). Опционально, по выбору пользователя по аналогии с отправлением уведомления на мыло и Pushover как еще один пункт в настройках web интерфейса. Скрипту параметрами передавать 
1. трекер обновленной/найденной раздачи
2. название обновленной/найденной раздачи (возможно и с фразой о добавлении/недобавлении в клиент - $message)
3. id раздачи + id торрент-файла - по возможности. Насколько знаю раньше ее (возможности) на шаге отправки уведомления не было, но вдруг в 1.1 это стало реальным.
4. может еще у кого будут какие идеи
Замучался при каждом выходе новой версии корректировать /torrentmonitor/class/Notification.class.php

**Comment by Jeronyson** [comment]
@cisco2 так если у вас это есть - выложите на всеобщее осмотрение)) Для каких целей вы это используете?

**Comment by cisco2** [comment]
@Jeronyson , /torrentmonitor/class/Notification.class.php строка 90: 
Notification::sendMail($sendUpdateEmail, $date, $tracker, $message, $header_message, $name);
закомментируй и замени на
print(`/bin/MyScript.sh "{$tracker}" "{$message}"`); 
Вместо отправки мыла будет вызываться скрипт c двумя параметрами, где
$message="$name обновлен."+фраза о добавлении/недобавлении в торрент клиент.
($name - имя раздачи). 
У меня вместо штатного ТМ-овского оповещения на мыло  шлет sms-ки днем, мыло ночью + логирование + еще кому что взбредет в голову. Предлагаю сделать по аналогии с мылом и пушовером - еще одно (третье) окно "вызов скрипта" - а в самом окне вводить путь/имя до него.

**Comment by vlmaksime** [comment]
https://github.com/ElizarovEugene/TorrentMonitor/pull/140
Здесь как-раз таки обсуждается создание более универсального способа оповещений с возможностью выбора службы уведомлений.

**Comment by ZeBriD** [comment]
Если мои правки в #140 примут, то реализовать подобное не составит особого труда.

**Comment by cisco2** [comment]
Почитал. Интересно, но ИМХО самый лучший способ - это тот, к которому привык ты сам. :-) Сколько людей, столько и привычек. Пушоверами и пушбулетами не пользуюсь. Делать под хотелки каждого - нереально. Сторонник того, чтобы сделать один стандартный вызов, передать ему максимум (достаточный разумный минимум) возможных  параметров, а дальше уж каждый сам под свои желания в него может включить вызов хоть своей любимой оповещалки/свистелки, хоть еще чего он придумает.

**Comment by Jeronyson** [comment]
@cisco2 так там так и планируют сделать :)
