### ISSUE TITLE
Casstudio.tv перешел на новый движок

### ISSUE THREAD

**Issue by cisco2** [ElizarovEugene/TorrentMonitor#122]
Casstudio.tv перешел на новый движок, поменялось все.
http://casstudio.tv/viewtopic.php?f=31&t=2

**Comment by ElizarovEugene** [comment]
Спасибо. Я вот даже залогиниться не смогу...

**Comment by vlmaksime** [comment]
Беда с этим треккером. Поставил я на нем закачку ходячих мертвяков http://casstudio.tv/details.php?id=1459
И что я вижу, при каждой проверке обновлений происходит установка торрента на закачку.
Достаточно зайти на вкладку "Запкуск" несколько раз, чтоб это увидеть.
Да, и в логах страницы "Запуск" для треккера в лог выводится ссылка:
Ходячие мертвецы / The Walking Dead | Сезон 5, эпизоды 1-11 (16) | [2014 г. | ужасы, триллер, драма | WEB-DL 720p] (Fox) на трекере casstudio.tv
http://casstudio.tv/download/file.php?id=6542
При этом без переходна на новую строку. В результате следующая страка приклеивается к ссылке.
Пологаю, что это остатки отладочной информации.

**Comment by ElizarovEugene** [comment]
Пробйуте обновление

**Comment by vlmaksime** [comment]
Проблема ушла. Спасибо.

**Comment by vlmaksime** [comment]
В продолжение темы апгрейда движка.
Ссылка на топик: http://casstudio.tv/viewtopic.php?f=59&t=1459
При попытке открыть через ТМ открывается:http://casstudio.tv/details.php?id=1459
Нашел где это делается, пошел чинить :)

**Comment by vlmaksime** [comment]
Опять какая-то беда с треккером. Теперь при обновлении раздачи он обнуляет время изменения раздачи и при каждом обновлении информации по раздаче по новой добавляет торрент

**Comment by ElizarovEugene** [comment]
По хэшу то конечно можно, но как юзер будет определять когда она обновилась то? Или тогда время будет соответствовать не времени обновления на трекере, а времени запуска ТМ, что тоже не совсем верно. Надо подумать...

**Comment by vlmaksime** [comment]
Можно извратиться и попытаться вычислить время по данным поля "Добавлено", но как по мне, это изврат. Например сейчас там написано:
Добавлен: Вчера, 22:07

Привязываемся к хэшу, если в поле "Добавлено" не удалось получить дату, то ставим текущую дату. Учитывая, что в моем случае ТМ обновляет данные каждые 10 минут, дата будет приблизительно точная. Погрешность возникнет только в том случае, если ТМ какое-то время не работал.

Ну или такой вариант.
Пытаемся получить дату из поля "Добавлено".
Если ДатаДобавлено = ПустаяДата 
      И НЕ Хэш = СтарыйХэш Тогда
        ДобавляемРаздачу();
        ДатаРаздачи = ТекущаяДата();
    КонецЕсли;
ИначеЕсли НЕ ДатаДобавлено = СтараяДата Тогда
    Если НЕ Хэш = СтарыйХэш Тогда
        ДобавляемРаздачу();
        ДатаРаздачи = ДатаДобавлено ;
   Иначе
        ДатаРаздачи = ДатаДобавлено ;
   КонецЕсли;
КонецЕсли;

В таком случае, рано или поздно в дату обновления попадет фактическая дата одновления раздачи.

**Comment by ElizarovEugene** [comment]
Вот как раз со "Вчера, 22:07" проблем никаких нет. С "Х минут назад" в общем то тоже, сейчас просто надо собрать все варианты времени, которое там указывается и я его буду преобразовывать в нормальный timestamp.

пс простите, но код с 1С-стайл я читать не в состоянии, у меня глаза в кучку :)

**Comment by vlmaksime** [comment]
@ElizarovEugene ну извените, 3 года стажа дают о себе знать :)
Тогда Вам проще будет забрать точное время с момента добавления раздачи:
```<td><b>Добавлен</b>: <span class="my_tt" title="1 час 59 минут 17 секунд назад">Вчера, 22:07</span></td>
```

**Comment by vlmaksime** [comment]
Заметил, что на 2й день раздачи сбивается время. Я наверно кинул не корректный пример со временем. На 2й день раздачи в классе my_tt появляется день, а дата добавления становится Вчера 12:12. Вот полный пример даты для парсинга.
```
<span class="my_tt" title="1 год 6 месяцев 29 дней 1 час 11 минут 41 секунду назад">
```

**Comment by ElizarovEugene** [comment]
>а дата добавления становится Вчера 12:12

ну вообще он корректно должен её преобразовывать.
а что внутри тега span то находится? он его содержимое парсит и анализирует, а не title

**Comment by vlmaksime** [comment]
внутри тега находится разница между текущей датой и датой добавления раздачи, взял с этой раздачи:http://casstudio.tv/viewtopic.php?f=158&t=606
Выявил эту проблему на раздаче ходячих:http://casstudio.tv/viewtopic.php?t=1459 
Раздача обновилась 17.03.15 в 00.50, весь день в списке была дата 17.03.15, но сейчас она стала 16.03.15

**Comment by ElizarovEugene** [comment]
А у вас временная зона верно выставлена? У меня у прова авария на оборудовании, я до сервака достучаться не могу, но тестово на моей машине возвращает правильное время
echo dateStringToNum('Вчера, 00:50'); //2015-03-17 00:50:00

**Comment by vlmaksime** [comment]
странно, сейчас пишет дату 17.03.15
Может сбойнуло из-за того, что обновление произошло около полуночи. Как вариант, время на моем сервере отстает на пару минут от их. из-за этого на загруженной странице было "Вчера", а у меня все еще 17е.
тогда вопрос закрыт

**Comment by ElizarovEugene** [comment]
Да, вероятнее всего проблема в этом, не думаю что это связано с преобразованием даты

**Comment by vlmaksime** [comment]
Да, так и есть. Сейчас зашел на страницу раздачи, на часах 18.03.15 1:00, время создания раздачи 1 день 1 час 15 минут назад. Прибавим это время ко времени начала раздачи 17.03.15 0.50 и получим что на сервере время 18.03.15 2.05.
Происходит коллизия в 1час и 5 минут. Не пойму, откуда такая разница. Зато я в разделе настроек нашел очень интересную опцию.
В разделе личных настроек, есть пункт "Формат даты:" и там я могу вывести дату как "менее минуты назад /18 мар 2015, 02:17" или "18 мар 2015, 02:17". Поставил 2й вариант и в раздачах теперь всегда стоит дата и время.

**Comment by ElizarovEugene** [comment]
>Поставил 2й вариант и в раздачах теперь всегда стоит дата и время.

ну тогда гарантированно не должно больше возникать данной проблемы
