### ISSUE TITLE
Проблема с temp.path

### ISSUE THREAD

**Issue by vlmaksime** [ElizarovEugene/TorrentMonitor#124]
Переношу обсуждение комментария http://blog.korphome.ru/torrentmonitor/#comment-1282 сюда.

Не глядя в код предположу, что при добавлении записи в temp уже добавляется path преобразованный в url

**Comment by ElizarovEugene** [comment]
Лучше уже сюда :) http://korphome.ru/TorrentMonitor/

**Comment by ElizarovEugene** [comment]
Я, если честно, совершенно запутался в том что вы написали в камменте. Про формирование пути, я сегодня одну человеку уже расписывал
https://github.com/chemodun/TorrentMonitor/commit/7ecc42cc20a3cfb6b9bdaf28df0348317258e481#commitcomment-9931311
Ссылки формируются при сохранении torrent-файла и одни и те же ссылки передаются как в клиент, так и записываются в таблицу temp. URL никак там не обновляется и не изменяется.

**Comment by vlmaksime** [comment]
На блоке у меня комментарии не работют :(

Я специально указал не верный адрес сервера. При первом запуске я имею такие данные
$path=/mnt/HD/HD_a2/Nas_Prog/torrentmonitor/php/torrents/[rutracker.org]_4929619.torrent
$url=http://localhost:81//mnt/HD/HD_a2/Nas_Prog/torrentmonitor/php/torrents/[rutracker.org]_4929619.torrent
$dir=/mnt/HD/HD_a2/Nas_Prog/torrentmonitor/php/
$url=http://localhost:81/torrents/[rutracker.org]_4929619.torrent
При добавлении торрента происходит ошибка и он попадает в temp
при повторном запуске пытаемся добавить торренты из tmp и получаем следующее
$path=http://localhost:81/torrents/[rutracker.org]_4929619.torrent
$url=http://localhost:81/http://localhost:81/torrents/[rutracker.org]_4929619.torrent
$dir=/mnt/HD/HD_a2/Nas_Prog/torrentmonitor/php/
$url=http://localhost:81/http://localhost:81/torrents/[rutracker.org]_4929619.torrent

Все из-за того, что при первом добавлении path равен локальному пути, а при втором равен ссылке.

**Comment by vlmaksime** [comment]
на досуге посмотрел код. Кажись нашел, что надо править
в модуле System.class.php в строке 289 строку:
            Database::saveToTemp($id, $url, $hash, $tracker, $message, $date_str);
Заменить на 
            Database::saveToTemp($id, $path, $hash, $tracker, $message, $date_str);
И проблема с неверным url ушла в небытие. :)
