### ISSUE TITLE
Transmission RPC

### ISSUE THREAD

**Issue by vlmaksime** [ElizarovEugene/TorrentMonitor#127]
При попытке добавить раздачу в Transmission с неверным логином/паролем вылетает по ошибке:
Fatal error: Uncaught exception 'TransmissionRPCException' with message 'Invalid username/password.' in /mnt/HD/HD_a2/Nas_Prog/torrentmonitor/php/class/TransmissionRPC.class.php:557 Stack trace: #0 /mnt/HD/HD_a2/Nas_Prog/torrentmonitor/php/class/TransmissionRPC.class.php(471): TransmissionRPC->GetSessionID() #1 /mnt/HD/HD_a2/Nas_Prog/torrentmonitor/php/class/TransmissionRPC.class.php(337): TransmissionRPC->request('session-get', Array) #2 /mnt/HD/HD_a2/Nas_Prog/torrentmonitor/php/class/TransmissionRPC.class.php(599): TransmissionRPC->sget() #3 /mnt/HD/HD_a2/Nas_Prog/torrentmonitor/php/class/Transmission.class.php(17): TransmissionRPC->__construct('http://localhos...', 'login', 'password') #4 [internal function]: Transmission::addNew('5', 'http://localhos...', '494d69422ce7b09...', 'casstudio.tv') #5 /mnt/HD/HD_a2/Nas_Prog/torrentmonitor/php/class/System.class.php(281): call_user_func('Transmission::a...', '5', 'http://localhos...', '494d69422ce7b09...', 'casstudio.tv') #6 /mnt/HD/HD_a2/Nas_Prog/torrentmonitor/php/cl in /mnt/HD/HD_a2/Nas_Prog/torrentmonitor/php/class/TransmissionRPC.class.php on line 557

Похоже, что надо отловить исключение и корректно его обработать, записать в ошибки сообщение с ошибкой. Сейчас же ничего туда не пишет.

**Comment by ElizarovEugene** [comment]
Какая версия Transmission?
Вообще он должен корректно возвращать http error 401: Unauthorized

**Comment by vlmaksime** [comment]
2.84

**Comment by ElizarovEugene** [comment]
Ну вообще на нём и тестил, завтра ещё разок проверю

**Comment by Upitep** [comment]
Fatal error: Uncaught exception 'TransmissionRPCException' with message 'Invalid username/password.' in /usr/local/www/data/class/TransmissionRPC.class.php:557 Stack trace: #0 /usr/local/www/data/class/TransmissionRPC.class.php(471): TransmissionRPC->GetSessionID() #1 /usr/local/www/data/class/TransmissionRPC.class.php(337): TransmissionRPC->request('session-get', Array) #2 /usr/local/www/data/class/TransmissionRPC.class.php(599): TransmissionRPC->sget() #3 /usr/local/www/data/class/Transmission.class.php(17): TransmissionRPC->__construct('http://192.168....', 'admin', '97a531b') #4 [internal function]: Transmission::addNew('1', 'http://192.168....', '', 'rutor.org') #5 /usr/local/www/data/class/System.class.php(281): call_user_func('Transmission::a...', '1', 'http://192.168....', '', 'rutor.org') #6 /usr/local/www/data/engine.php(131): Sys::addToClient('1', '/usr/local/www/...', '', 'rutor.org', 'rutor.org :: \xD0\x98...', '21 \xD0\x9C\xD0\xB0\xD1\x80 2015 ...') #7 /usr/local/www/data/include/execution.php(7): include_on in /usr/local/www/data/class/TransmissionRPC.class.php on line 557

Проблему подтверждаю, хотя этот момент в тестовой версии TransmissionRPC отлавливался.
