### ISSUE TITLE
rutracker, добавить оповещение "закрыто правообладателем"

### ISSUE THREAD

**Issue by kea255** [ElizarovEugene/TorrentMonitor#129]
Идеально с удалением из монитора и торент клиента.
что то вроде: 

```
if(strpos($page,'закрыто правообладателем')){
                    Notification::sendNotification('notification', date("Y-m-d"), $tracker, '<b>Закрыто правообладателем:</b> <a href="http://rutracker.org/forum/viewtopic.php?t='.$torrent_id.'">'.$name.'</a>');
                    Database::deletItem($id);
                    rutracker::$exucution = FALSE;
                }
```

**Comment by ElizarovEugene** [comment]
Нет, молча удалять это не правильно. Лучше к заголовку приписывать соответствующее уведомление - будет и понятно и заметнее.

**Comment by vlmaksime** [comment]
Раз уж такая пляска, может в таблицу торрентов добавить флаг активности. Если раздача закрыта, то мы флаг снимаем, и больше ее не анализируем. Ну и это даст возможность пользователям управлять раздачами, не удаляя их из списка.

**Comment by ElizarovEugene** [comment]
Пока я решил что сюда же надо прикрутить удалённые раздачи, иногда и такое бывает
@vlmaksime а я не очень понимаю смысл держать в ТМ раздачи, за которыми не следят...

**Comment by kea255** [comment]
Статус раздачи добавить. Удаленные и закрытые выделять красным цветом + в настройках возможность автоудаления.

**Comment by vlmaksime** [comment]
@ElizarovEugene возможно в повседневной жизни этот флаг и не пригодиться, но для данного примера будет вполне актуален. Если раздача удалена/закрыта, то зачем лишний раз делать запрос к странице? Так сказать в целях оптимизации

**Comment by ElizarovEugene** [comment]
@kea255 ок
@vlmaksime ну так одно делать это для автоматического режима, а другое дело ручные настройки проверки

**Comment by Bugemon** [comment]
Еще есть статус "Поглощено", при котором в последнем сообщении дают ссылку на другую раздачу.

**Comment by vlmaksime** [comment]
@ElizarovEugene Ну флаг активности полюбому надо будет вывести пользователю.
Например есть у меня есть настроенная закачка сверхестественных. Как сказал @Bugemon, ее поглатили. При попытке оновить раздачу ТМ видит, что она поглащена, снимает флаг активности и взводит соответствующий статус. Я, когда захожу в ТМ, вижу сие безобразие, нахожу новый источник, меняю на него ссылку в существующей раздаче и взвожу флаг активности. Ну или флаг активности можно взводить автоматом при сохранении параметров раздачи.

У меня тут созрел один сценарий:
Если у меня раздача с rutracker.org, а я ссылку поменяю на casstudio.tv, то строка парсится правильно, из нее выдерается правильный id раздачи, но при этом треккер не переключается с rutracker.org на casstudio.tv
