### ISSUE TITLE
Ошибки скрипта

### ISSUE THREAD

**Issue by 876974** [ElizarovEugene/TorrentMonitor#131]
При выполнении скрипта по крону периодически на почту приходят ошибки с текстом:
PHP Notice:  Trying to get property of non-object in /***/tor/class/System.class.php on line 370

Так же при выпуске новой версии не было получено письма с уведомлением о новой версии при включенной опции уведомления о новых версиях

**Comment by ElizarovEugene** [comment]
Странно, видимо что то с чтением xml файла новостей, посмотрю
А где вы увидели опцию уведомления о новых версиях? :))))

**Comment by psvmcc** [comment]
Видимо имеется ввиду "Отправлять уведомления об обновлениях", но тут под обновлениями подразумевается обновления не TM, а торрентов за которыми ТМ следит.

**Comment by 876974** [comment]
Прощу прощения, думал что это опция о появлении новой версии скрипта, но было бы так же не плохо реализовать данную возможность. Так как захожу в скрипт не слишком часто, и хотелось бы знать о выходе новых версий, с какими либо исправлениями.

**Comment by ElizarovEugene** [comment]
@876974 да эта галка там вроде всегда была :)
этот вопрос мы сейчас как раз обсуждаем http://korphome.ru/TorrentMonitor/viewtopic.php?f=5&p=26
