### ISSUE TITLE
Pushbullet

### ISSUE THREAD

**Issue by 876974** [ElizarovEugene/TorrentMonitor#132]
В скрипте реализована поддержка Pushover, но так как пользуюсь сервисом Pushbullet который имеет больше возможностей от первого реализованного, хотелось бы надеяться на реализацию поддержки данного сервиса уведомлений.

**Comment by ElizarovEugene** [comment]
Надо API почитать, в принципе преград никаких для этого нет

**Comment by vlmaksime** [comment]
Не хочу создавать новую тему, предложу здесь. Предлагаю немного переделать раздел настроек, связанный с уведомлениями. Сделать его следующим образом:
```Раздел служб для рассылки
    //Здесь будут задаваться параметры для рассылки
    Поле вводе e-mail для отправки уведомлений
    Выпадающий список для выбора службы Push-уведомлений
    Token для доступа к службе
Раздел для настройки уведомлений
    Оповещения
        Оповещать по e-mail
        Оповещать через Push
    Предупреждения
        Оповещать по e-mail
        Оповещать через Push```
Не думаю, что кто-то будет пользоваться разными ящиками/сервисами для получения уведомлений.
