### ISSUE TITLE
Clear error log action [warning table]

### ISSUE THREAD

**Issue by psvmcc** [ElizarovEugene/TorrentMonitor#133]
Привет,

Не плохо б добавить кнопочку очистки лога ошибок, у меня их скопилось несколько тысяч, пришлось руками в базе сделать: delete from warning;

**Comment by cisco2** [comment]
Каким то образом они там чистятся, но не всегда - инода тоже приходится ручками.

**Comment by vlmaksime** [comment]
Согласно коду, после успешной операции все сообщения, связанные с этим треккером/событием, удаляются

**Comment by psvmcc** [comment]
Да похоже удаляются, видимо у меня был какой то "глюк", если еще раз появится попробую разобраться более детально.

**Comment by psvmcc** [comment]
И все же кнопочка нужна имхо. У меня получилась другая ситуация.
Была единственная раздача на NovaFilm за которой следил, потом ее удалил из ТМ, по причине что в данный момент мне этот сериал не интересен, и тут совпало что ранее с ним были ошибки, те я удалил его до фикса со стороны NovaFilm, либо оно до сих пор сломано :)
![screenshot 2015-03-23 11 23 57](https://cloud.githubusercontent.com/assets/2987792/6777108/1d9b4d8e-d14f-11e4-9c93-4fcb2591a268.png)

**Comment by Upitep** [comment]
Если и удалять, то не все разом, а с выбором по конкретному трекеру :)
