### ISSUE TITLE
Warning при обновлении

### ISSUE THREAD

**Issue by vlmaksime** [ElizarovEugene/TorrentMonitor#135]
Получил эти предупреждения при попытке перейти с версии 1.0.5 на 1.1.
```
Warning: Invalid argument supplied for foreach() in /mnt/HD/HD_a2/Nas_Prog/torrentmonitor/php/include/update.php on line 50

Warning: Invalid argument supplied for foreach() in /mnt/HD/HD_a2/Nas_Prog/torrentmonitor/php/include/update.php on line 54
```
Когда в версии 1.1. вручную понизил версию до 1.0.6, то при обновлении получаю 
```
Warning: Invalid argument supplied for foreach() in /mnt/HD/HD_a2/Nas_Prog/torrentmonitor/php/include/update.php on line 55
```

**Comment by ElizarovEugene** [comment]
ммм, так а какая у вас по факту версия то стоит?

**Comment by vlmaksime** [comment]
Изначально стояла версия 1.0.6, обновился до последней актуальной 1.1, получил 2 ошибки. Помниться, Вы правили файл Update.php, думаю дай проверю, может это ошибка в версии была. Зашел в system.php и поменял версию с 1.1 на 1.0.6, зашел в интерфейс и обновился еще раз. Получил одну ошибку, но уже в другой строке.

**Comment by ElizarovEugene** [comment]
Сейчас у себя поменял на 1.0.6 - ошибок не получил...
>on line 55
там вроде кроме как чтения xml ничего нет...

**Comment by vlmaksime** [comment]
Кажется нашел причину предупреждений.
Откатил версию до 1.0.5, получил еще больше предупреждений:
```
Changelog for 1.0.6:
Warning: Invalid argument supplied for foreach() in /mnt/HD/HD_a2/Nas_Prog/torrentmonitor/php/include/update.php on line 55
Warning: Invalid argument supplied for foreach() in /mnt/HD/HD_a2/Nas_Prog/torrentmonitor/php/include/update.php on line 59
Warning: Invalid argument supplied for foreach() in /mnt/HD/HD_a2/Nas_Prog/torrentmonitor/php/include/update.php on line 82
Warning: Invalid argument supplied for foreach() in /mnt/HD/HD_a2/Nas_Prog/torrentmonitor/php/include/update.php on line 89

Changelog for 1.1:
Warning: Invalid argument supplied for foreach() in /mnt/HD/HD_a2/Nas_Prog/torrentmonitor/php/include/update.php on line 55
```
Во всех этих местах выполняется обход по элементам массива при помощи foreach.

При переходе на версию 1.1 ругается на 55ю строку:
```
 foreach($deleteFolders->folder as $folder)
```
пытаемся обойти массив "folder" из группы deleteFolders. В нашем случае он пустой.
```
deleteFolders:
object(SimpleXMLElement)#12 (0) { }
```
на 59ю строку
```
foreach($createFolders->create as $folder)
```
не ругнулся, т.к. для нее есть массив папок:
```
createFolders:
object(SimpleXMLElement)#5 (1) { ["folder"]=> array(2) { [0]=> string(3) "rss" [1]=> string(8) "torrents" } }
```
Так же есть изменения в структуре БД, из-за этого не ругнулось при обходе запросов в строках 82 и 89.
При переходе с 1.0.5 на 1.0.6 были добавлены только файлы. Из-за этого и получили такое количество ошибок.

Я запускал это на PHP версии 5.4.38, возможно на Вашей версии в этом месте не ругается ошибками.

Я поличил эту предупреждения, создал Pull Request
