### ISSUE TITLE
Снова проблема с lostfilm

### ISSUE THREAD

**Issue by thunder-spb** [ElizarovEugene/TorrentMonitor#137]
Примерно дня 4 назад началось, приходит на почту предупреждение с пустым полем "Сообщение" :(

эм. после обновления пропали все торренты от лостфильма... в changelog ничего такого не написано... от lostfilm отказались??

**Comment by vlmaksime** [comment]
Да, @ElizarovEugene выпилил его, т.к. он не стабильно работает из-за CloudFire.
Об этом упоминалось в комментариях в блоге, в коммитах на GitHub'e, ну и в TorrentMonitor'e на вкладке "Новости"

**Comment by thunder-spb** [comment]
эх, понятно, спасибо... почти все сериалы были с него :((((

**Comment by vlmaksime** [comment]
@thunder-spb а я только для него и ставил TM

**Comment by thunder-spb** [comment]
кстати последняя загрузка с лоста была неделю назад :))) поэтому это скорее какаято местная проблема...

**Comment by vlmaksime** [comment]
ну Вам скорее всего повезло. Подождем, что скажет @ElizarovEugene

**Comment by ElizarovEugene** [comment]
@thunder-spb спасибо, чэйнджлог поправил
LF выпилил по двум причинам, корнем которых является cloudflare и нежелание админов сказать хоть слово http://www.lostfilm.tv/phpbb2.php?page=viewtopic&t=19317&postdays=0&postorder=asc&start=30
мне просто надоели эти грабли на самом деле, хотя я все почти сериалы смотрю с озвучкой лоста

**Comment by ElizarovEugene** [comment]
Не знаю что у вас там работает.....
[korp@transmission ~]$ curl --socks5 192.168.1.220:9100 http://www.lostfilm.tv/rssdd.xml
<title>Attention Required! | CloudFlare</title>

в общем через Tor - CloudFlare, на прямую - закрыто провайдером.

**Comment by psvmcc** [comment]
Тут по сути 2 проблемы, блокировка провайдерами в РФ(почему они это делаю вопрос, потому как на http://eais.rkn.gov.ru/ lostfilm.tv не фигурирует, возможно они блочат не lostfilm, а сети cloudflare) и сам cloudflare(который не пропускает трафик с прокси). У меня с трех различных локаций, не связанными между собой все отдается нормально:

Sergeys-MacBook-Air:~ psv$ curl http://www.lostfilm.tv/rssdd.xml -v
* Hostname was NOT found in DNS cache
*   Trying 104.28.17.79...
* Connected to www.lostfilm.tv (104.28.17.79) port 80 (#0)
> GET /rssdd.xml HTTP/1.1
> User-Agent: curl/7.37.1
> Host: www.lostfilm.tv
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Thu, 12 Mar 2015 06:51:01 GMT
< Content-Type: text/xml
< Transfer-Encoding: chunked
< Connection: keep-alive
< Set-Cookie: __cfduid=d40045ec8da72805f1f9ca66c2affa8721426143061; expires=Fri, 11-Mar-16 06:51:01 GMT; path=/; domain=.lostfilm.tv; HttpOnly
< Last-Modified: Wed, 11 Mar 2015 17:59:31 GMT
< Vary: Accept-Encoding
* Server cloudflare-nginx is not blacklisted
< Server: cloudflare-nginx
< CF-RAY: 1c5d91767d8e0c17-AMS
< 
<?xml version="1.0" encoding="windows-1251" ?>
<rss version="0.91">
<channel>
<title>LostFilm.TV</title>
.....
blablabla

**Comment by ElizarovEugene** [comment]
Вот что ответил мой пров:
>Я вкурсе этого прикола.
В веб форме его нет, а выгрузке которую мы делаем своим ключом есть http://vigruzki.rkn.gov.ru/tooperators_form/
Бюрократия против пиратства, пока бюрократы побеждают.

**Comment by psvmcc** [comment]
А с VPN не вариант? Есть же различные free решения, что дают какое то количества трафика. Поднять VPN с маршрутом только до lostfilm.tv, для закачки torrent файлов, я думаю тут 100MB в месяц хватит с головой. Или даже скачав torrent файл нет возможности подключиться torrent клиентом и получить список пиров/сидов, те весь траф нужно пускать через VPN?

**Comment by ElizarovEugene** [comment]
Да я как то привык всё у себя держать, даже не знаю про такие сервисы, надо погуглить, может и можно. Вообще знакомый где то держал за бугром сервак и раздавал всем впн за небольшую денежку, можно и с ним поговорить
по поводу сидов/пиров не знаю, на крайняк есть DHT для обмена клиентами

**Comment by Bugemon** [comment]
У ЛостФильма трекер находится на другом домене, и его не блокируют.
Главное с лоста, точнее даже не с лоста, а с того же трекера tracktor.in скачать торрент файл

**Comment by psvmcc** [comment]
@Bugemon главное получить RSS, без него не узнать о файлике :)
@ElizarovEugene ни сколько не реклама, вот какие то 2 сервиса, писали на хабре https://www.frootvpn.com/ или https://www.tunnelbear.com/, сам не пробовал, просто добавил закладки.

**Comment by ElizarovEugene** [comment]
>а с того же трекера tracktor.in скачать торрент файл

главное в lostfilm.tv получить ссылку вовремя, скачивать с tracktor.in - проблем 0.
Самое главное - администрация не идёт ни на какие контакты. Я бы спокойно выделил у себя машину и даже отдельный IP под парсер именно RSS и открыл её в общий доступ, если бы они согласились организовать мне прямой доступ

**Comment by Bugemon** [comment]
@psvmcc rss можно получить через любой rss ридер, которых после закрытия гуглоридера множество, хотя бы через http://feeds.feedburner.com/

**Comment by ElizarovEugene** [comment]
@Bugemon здесь то речь идёт об автоматическом получении ленты при помощи парсера, а с ним есть проблемы из-за cloudflare

**Comment by Bugemon** [comment]
@ElizarovEugene чем вот эта лента хуже той, что на самом лосте?
http://feeds.feedburner.com/lostfilmtv/rssdd

**Comment by ElizarovEugene** [comment]
Да сама лента ни чем не хуже, проблема то в том, что ссылки на torrent-файлы ведут всё-равно на http://www.lostfilm.tv/download.php
Тут только 3 варианта:
1. Откроют доступ наши провы и возможно для наших IP не будет заглушка от cloudflare
2. Снимут cloudflare и можно будет работать спокойно через tor и прочие анонимайзеры без проблем
3. ЗЕРКАЛО lostfilm.tv
