### ISSUE TITLE
Дизайн для torrentmonitor.ru

### ISSUE THREAD

**Issue by ElizarovEugene** [ElizarovEugene/TorrentMonitor#141]
И так, уважаемые пользователи, хочу с вами посоветоваться.
Пора TM уже из странички в моём блоге обзавестись доменом и заиметь некий нормальный промо-сайт.
Если сайт я ещё накидаю, то с дизайном у меня совсем туго, а Татьяна, которая делала последнюю версию дизайна самого TM в последнее время не доступна.
В общем то - главный вопрос - сколько сейчас стоит макет одностраничника? Я от этих вопросов очень далёк - не моя специфика, по этому не очень владею вопросом.
Так же появилась идея - вместо того что бы идти на фриланс.ру и искать исполнителей там - устроить мини-конкурс на макет, который выберут сами пользователи, ну а победитель получит некую сумму денег от меня. Так сказать - народный выбор. Если всё пойдёт хорошо, можно и дизайн ТМ будет освежить, ну и ещё надо придумать какое то лого, а то иногда нужна иконка для приложения.

**Comment by vlmaksime** [comment]
Все что могу предложить, это шаблон моей странички, которую я делал при выпуске из магистратуры. Посмотреть на это "чудо" можно тут:
http://masters.donntu.org/2011/fknt/maksimenko/

**Comment by ElizarovEugene** [comment]
Да, я для диплома то же как то рисовал шаблончик :)
http://monosnap.com/image/5ZpakXDTQdaB9fiKmUOtWkIUPv3L6G
Жаль его в жизнь не удалось притворить...даже на халяву :(

**Comment by Jeronyson** [comment]
Twitter Bootstrap, как вариант? Прост в освоении, бесплатно, гибко (поддержка всего и вся: старые звонилки, андроиды, айфоны, планшеты, ноутбуки...)

**Comment by ElizarovEugene** [comment]
>Прост в освоении

вот честно - мне и без него есть чем себя занять :)))

**Comment by Jeronyson** [comment]
@ElizarovEugene ну для начала можно разделить php и html, и прикрутить или сделать механизм шаблонизатора с возможностью выбора тем, а затем можно уже делать новый дизайн.
Ну в качестве примера, в корне есть папка themes, в которой будет папка default и там, соответственно, шаблоны разных страниц (ну, например, main.tpl), и в каждой странице вызывается движок шаблонизатора, который подгружает необходимую тему (установленную в настройках).
Почему так?
1. Простота. Когда новая тема будет готова - достаточно добавить папку с ней в директорию themes
2. Удобство. Темы легко редактировать без знания PHP, что дает возможность пользователям создавать свои темы (а в последствии можно сделать общедоступный репозиторий тем)
3. Эстетичность. Разделение PHP и HTML является хорошим тоном. И к тому же, это реально удобнее.

**Comment by ElizarovEugene** [comment]
@Jeronyson ну что такое шаблонизаторы и все вытекающих из них блага мне известны, но в моём скудном опыте программирования - опыт работы с ними отсутствует совсем. учитывая что php я сейчас использую только для проекта ТМ, а программирование в целом не является для меня сферой деятельности - углубляться в изучение чего то ещё - банально нет времени :( Если кто то возьмётся за реализацию шаблонизатора - я буду только рад

**Comment by thunder-spb** [comment]
слишком сильно все захардкожено((( тяжко будет

**Comment by vlmaksime** [comment]
Я практически закончил с разделением кода и интерфейса. При желании, можно будет прикрутить сменные темы.

**Comment by thunder-spb** [comment]
отличные новости!
