### ISSUE TITLE
Баг kinozal.tv

### ISSUE THREAD

**Issue by Jeronyson** [ElizarovEugene/TorrentMonitor#144]
**Такая ситуация с кинозалом:**
При обновлении раздачи на кинозале, TM в большинстве случаев перекачивает торрент и отправляет уведомление дважды, с интервалом в 10 минут (крон). Я выяснил почему.

**Источник проблемы.**
Дебилизм кинозала в виде "сейчас", вместо "сегодня в XX:XX"

**Почему.**
На кинозале в поле, когда был обновлен торрент указывается "сейчас", если торрент был обновлен три и менее минут назад. То есть, если торрент был обновлен в 14:37, а TM запустился в 14:39, то будет написано "сейчас". НО! ТМ в таком случае запишет, что раздача была обновлена в 14:39, потому что он не знает, когда она действительно была обновлена и пишет текущее время (то есть время запуска скрипта).
Соответственно, при следующем запуске крона (в 14:49) он откроет страницу раздачи и увидит "сегодня в 14:37", но в базе ТМ записано, что раздача была обновлена в 14:39. Так как время не равно, то он еще раз обновит торрент и отправит уведомление.

**Решение:**
Вместо
` ЕСЛИ время_на_странице != время_в_базе ТО обновить_торрент `
сделать так:
` ЕСЛИ время_на_странице > время_в_базе ТО обновить_торрент `

trackers/kinozal.tv.engine.php (строка 192):
```php
if ($date != $timestamp)
```

**А теперь, интересный бонус:**
Пока копался, случайно нашел дырку в кинозале, которая позволяет смотреть журнал редактирования любой раздачи. Такая страничка значительно легче и быстрее загружается.
Линк подобного вида: `http://kinozal.tv/get_srv_details.php?id=ID_РАЗДАЧИ&action=12`

Возвращает подобную страничку ( http://kinozal.tv/get_srv_details.php?id=1316086&action=12 ):
```
сейчас - Раздача выставлена (1316086) изм. от: igorella87 (6258916)
сегодня в 14:23 - Раздача Последний из Магикян (4 сезон: 1-20 серии из ... (1316086) изм. от: zeka80 (1852312)
сегодня в 14:23 - Торрент обновлен (1316086) изм. от: zeka80 (1852312)
сегодня в 14:22 - Комментарий №3466111 от 1852312 удалил zeka80 (1852312) раздача: (1316086)
сегодня в 12:50 - Комментарий №3467110 от 19415710 удалил zeka80 (1852312) раздача: (1316086)
вчера в 14:49 - Раздача выставлена (1316086) изм. от: Karamelika (3130224)
вчера в 14:35 - Раздача Последний из Магикян (4 сезон: 1-19 серии из ... (1316086) изм. от: zeka80 (1852312)
вчера в 14:35 - Торрент обновлен (1316086) изм. от: zeka80 (1852312)
вчера в 14:34 - Комментарий №3464960 от 1852312 удалил zeka80 (1852312) раздача: (1316086)
...
...
...
```

**Comment by cisco2** [comment]
На касстудио что-то похожее. При перезаливке торрент-файла на странице раздачи указывается "Добавлен: 3 минуты назад" и т.д. до "59 минут назад".
В течении этого часа ТМ при каждом запуске по крону находит обновление раздачи, в базе в таблице timestamp по этой раздаче время нулевое , старую раздачу из клиента удаляет и добавляет новую.

**Comment by vlmaksime** [comment]
@cisco2, у них в настройках можно поменять формат представления времен. можно поставить, чтоб всегда выводилось время добавления раздачи

**Comment by cisco2** [comment]
@vlmaksime СПС, вроде помогло. "Профиль - личные настройки - общие настройки". Формат даты на страницах раздач поменялся, посмотрим как пройдут перезаливки этих раздач. Прямо хоть фак пиши - изменить на трекере в профиле настройки даты по умолчанию.

**Comment by Jeronyson** [comment]
Понял, что это решение тоже неидеально. В довесок можно проверять и hash торрента, что будет являться 100% показателем обновления торрента, потому что шанс коллизии слишком мал.

**Comment by vlmaksime** [comment]
@Jeronyson, это уже обсуждалось тут: https://github.com/ElizarovEugene/TorrentMonitor/issues/122#issuecomment-76774009

**Comment by Jeronyson** [comment]
@vlmaksime ну насколько вижу, это ни к чему не привело.

Конкретно для кинозала такое предложение:
Использовать проверку по хешу, только если видим вместо времени слово "сейчас". И если время изменилось, а хэш - нет, то просто правим время обновления раздачи (чтобы оно соответствовало тому времени, которое указано на трекере), но при этом торрент не обновляем. Так и время верное будет - и по два раза не надо обновлять торрент.

**Comment by vlmaksime** [comment]
@Jeronyson, проблема в том, что даже через какое-то время в раздаче продолжает висет "Сейчас". В таком случае каждый раз в базу будет загоняться время запуска проверки.

**Comment by ElizarovEugene** [comment]
Ну видимо на casstudio то же произошли какие то изменения, или я просто этого не доглядел когда писал, в ТМ сейчас нет обработки формата "59 минут назад". Надо просто его доделать и всё будет правильно отображаться, а не ломать голову с хэшем, он будет верно время указывать.

**Comment by Jeronyson** [comment]
@vlmaksime опытным путем выяснил, что Сейчас висит только 3 минуты после обновления торрента, а потом уже начинает Сегодня в XX:XX

**Comment by ElizarovEugene** [comment]
@Jeronyson так подождите, вариант "Сегодня в XX:XX" должен отрабаывать корректно. Так же как и "Вчера в XX:XX", после чего он отображает дату в формате регулярки "\d{1,2} \D* \d{4}, \d{2}:\d{2}". Откуда тогда берётся "59 минут назад"?

**Comment by Jeronyson** [comment]
@ElizarovEugene я говорю о кинозал.тв, а @vlmaksime о касстудио говорил.
Не спорю, что вариант Сегодня в XX:XX отрабатывается корректно, проблема в варианте Сегодня. Прочитайте первый пост, я там подробно описал в чем проблема. У меня очень часто раздачи с кинозала обновляются дважды, из за этого Сейчас.

**Comment by Jeronyson** [comment]
@ElizarovEugene например сегодня:
![kinozal](https://pp.vk.me/c623129/v623129035/2465d/G1wi6h9upwQ.jpg)

**Comment by ElizarovEugene** [comment]
А я уже запутался похоже...с кинозалом же мы решили что просто != нужно заменить на > и вся проблема решится...нет?

**Comment by Jeronyson** [comment]
@ElizarovEugene нет, я это потом понял.
Возьмем конкретный пример. Скрипт запускается в 14:10, 14:20 и т.д.
Раздача обновилась в 14:08. Скрипт запустился в 14:10 (но он видит "сейчас"), обновляется торрент, пишем, что раздача обновлена в 14:10. Но время еще 14:10. И если раздачу опять обновят, в 14:10 (такое бывает, косяк в торренте, например), то при следующем запуске мы увидим, что раздача была обновлена в 14:10 и мы ее уже обновляли в 14:10 (хотя торрент файл может быть уже другой).
То есть, есть от 0 до 60 секунд, которые скрипт не отслеживает. Время малое, шанс попадания в такую ситуацию тоже мал, но в таком случае пользователь должен обнаружить, что торрент недействителен и обновить вручную. Если добавить проверку по хешу, то торрент 100% будет всегда действительным.

**Comment by Jeronyson** [comment]
```
ЕСЛИ хеш_в_базе != хеш_на_странице ТО
    ЕСЛИ время_на_странице == "Сейчас" ТО
        время_в_базе = текущее_время
    ИНАЧЕ
        время_в_базе = время_на_странице
    КОНЕЦ ЕСЛИ
    обновить_торрент_и_добавить_в_клиент()
ИНАЧЕ
    ЕСЛИ (время_в_базе != время_на_странице) И (время_на_странице != "Сейчас) ТО
        время_в_базе = время_на_странице
    КОНЕЦ ЕСЛИ
КОНЕЦ ЕСЛИ
```

Объясню алгоритм. Торрент обновляется только если хеш на странице раздачи, не такой как в базе. Иначе, мы проверяем время обновления раздачи, чтобы оно в базе было правильным, но при этом торрент не обновляем (хеш то не поменялся).

**Comment by Jeronyson** [comment]
Хеш можно получить с этой страницы:
`http://kinozal.tv/get_srv_details.php?id=ID_РАЗДАЧИ&action=2`

Пример:
http://kinozal.tv/get_srv_details.php?id=1314647&action=2
```
Инфо хеш: 1BA7D9502AD77C3CA075E7805CEE7B64D3157F97
Размер части торрента: 4 МБ
The.Jinx.The.Life.and.Deaths.of.Robert.Durst.(s01).HDTV.720p.x264-RUS-ENG-lrn
The.Jinx.The.Life.and.Deaths.of.Robert.Durst.(s01e01).HDTV.720p.x264-RUS-ENG-lrn.mkv 1.32 ГБ (1419589934)
The.Jinx.The.Life.and.Deaths.of.Robert.Durst.(s01e02).HDTV.720p.x264-RUS-ENG-lrn.mkv 1.42 ГБ (1521412947)
The.Jinx.The.Life.and.Deaths.of.Robert.Durst.(s01e03).HDTV.720p.x264-RUS-ENG-lrn.mkv 1.35 ГБ (1454517367)
The.Jinx.The.Life.and.Deaths.of.Robert.Durst.(s01e04).HDTV.720p.x264-RUS-ENG-lrn.mkv 1.57 ГБ (1687008271)
The.Jinx.The.Life.and.Deaths.of.Robert.Durst.(s01e05).HDTV.720p.x264-RUS-ENG-lrn.mkv 1.42 ГБ (1525706224)
The.Jinx.The.Life.and.Deaths.of.Robert.Durst.(s01e06).HDTV.720p.x264-RUS-ENG-lrn.mkv 1.17 ГБ (1252160047)
```

**Comment by ElizarovEugene** [comment]
Вообще проблема решается установкой рекомендуемого времени обновления раз в 10 минут. Получать каждый раз дополнительную страницу - не кажется мне хорошей идеей, ввиду того что это увеличивает время работы системы в общем.

**Comment by vlmaksime** [comment]
@ElizarovEugene, как по мне, то и 10 минут это часто. Поставил себе обновление раз в 90 минут, всеравно не успеваю смотреть все, что выходит.

**Comment by ElizarovEugene** [comment]
@vlmaksime тут есть просто ещё один момент - более частая проверка, чем раз в 10 минут, на некоторых трекерах приводит к появлению капчи из-за частых релогинов и потом на несколько часов вообще придётся стопать ТМ иначе капча не пропадёт. Ну а в большую сторону - тут уже кому как, кому и раз в неделю может хватит :)

**Comment by Jeronyson** [comment]
@ElizarovEugene частота обновления лишь уменьшает шанс двойного обновления, но не ликвидирует его.

**Comment by ElizarovEugene** [comment]
@Jeronyson вот сколько я уже кинозалом пользуюсь, с тех пор как у меня перестал лост работать - ни разу не сталкивался

**Comment by Jeronyson** [comment]
@ElizarovEugene у меня время запуска скрипта стоит раз в 10 минут. Есть две раздачи Универа, обновляются они в пн, вт, ср и чт. Так вот за 8 обновлений, стабильно 2-3 раза обновляется дважды.
Я же сегодня кидал скрин с "двойным обновлением"

**Comment by ElizarovEugene** [comment]
@Jeronyson ну то что ты кидал фиксится твоим же предложением сменить != на >, для этого не нужно привязываться с хэшу. Просто для меня это принципиальный вопрос - если мы переходим на использование хэша, то тогда мы это делаем для всех трекеров, ибо логика работы должна быть везде одинакова

**Comment by Jeronyson** [comment]
@ElizarovEugene тогда появляется шанс пропуска обновления в размере от 0 до 60 секунд. Мало, но шанс все равно есть.
А разве не затем разносились трекеры в отдельные классы, что работа с ними может быть принципиально разной?

**Comment by ElizarovEugene** [comment]
@Jeronyson Нет, разносились они не для этого и принцип работы у них у всех один в общем то. Ну точнее два, в зависимости от типа трекера.

**Comment by Upitep** [comment]
>@ElizarovEugene у меня время запуска скрипта стоит раз в 10 минут. Есть две раздачи >Универа, обновляются они в пн, вт, ср и чт. Так вот за 8 обновлений (одна неделя), стабильно 2->3 раза обновляется дважды.
>Я же сегодня кидал скрин с "двойным обновлением"

Если использовать торрент-клиент, то он просто не даст добавить существующую закачку еще раз :)

PS. Кстати, надо бы проверить Transmission.class.php на эту тему..

**Comment by ElizarovEugene** [comment]
Почему это не даст то? Он удалит предыдущую и снова добавит

**Comment by vlmaksime** [comment]
@ElizarovEugene, наверно имеет смысл прикрутить проверку хэша. Если хэш в торрент-клиенте равен хэшу в раздаче, то не обновлять. Да и после добавления файла, торрент клиент сначала перехеширует уже загруженные файлы а потом качает недостающее.

**Comment by Upitep** [comment]
>Почему это не даст то? Он удалит предыдущую и снова добавит

Да, не подумал - в логике ТМ это просто старая раздача.

**Comment by Jeronyson** [comment]
Вот опять. То есть всего из двух обновлений - оба обновились дважды. А вы
говорите проблемы нет...

понедельник, 23 марта 2015 г. пользователь Vladimir Maksimenko написал:

**Comment by Jeronyson** [comment]
![tttt](http://funkyimg.com/i/VaAL.jpg)

**Comment by ElizarovEugene** [comment]
@Jeronyson что то я вообще не пойму как оно у тебя так работает.
Смотри, как формируется время обновления, которе пишется в уведомление:
```
if (strstr($data, 'сейчас'))
	    {
	        $timestamp = strtotime('now');
	        $day = date('d', $timestamp);
			$month = Sys::dateNumToString(date('m', $timestamp));
			$year = date('Y', $timestamp);
	        $dateTime = $day.' '.$month.' '.$year.' в '.$pieces[2];
	        return $dateTime;
        }
```
те если там написано "сейчас" он тебе дату сгенерирует целиком, а у тебя там только дата. ощущение, что срабатывает другой if:
```
if (strstr($data, 'сегодня') || strstr($data, 'вчера'))
	    {
	        $pieces = explode(' ', $data);
	        if ($pieces[0] == 'вчера')
	            $timestamp = strtotime('-1 day');
	        else         
	            $timestamp = strtotime('now');
	        $day = date('d', $timestamp);
			$month = Sys::dateNumToString(date('m', $timestamp));
			$year = date('Y', $timestamp);
	        $dateTime = $day.' '.$month.' '.$year.' в '.$pieces[2];
	        return $dateTime;
	    }
```
в котором отсутствует кусов со временем, по этому у тебя там указана только дата.
А во второй раз он уже целиком видимо берёт время из раздачи. Дай ссылки на эти темы, поставлю у себя - посмотрю.

пс у меня есть ощущение, что у тебя на акутальная версия файла kinozal.tv.engine.php и отсутствует функция обработки "сейчас" https://github.com/ElizarovEugene/TorrentMonitor/commit/c6ec67e4bca308ed083eff03b97649481ec2b6ff#diff-0a66973e7c243da6bf87410b874ee386

**Comment by ElizarovEugene** [comment]
Да никто не говорил что проблемы нет

**Comment by Jeronyson** [comment]
@ElizarovEugene залил исправленный вариант.

**Comment by ElizarovEugene** [comment]
@Jeronyson куда? что то не вижу нигде

**Comment by Jeronyson** [comment]
@ElizarovEugene ну себе на сервер, имею ввиду.

**Comment by ElizarovEugene** [comment]
ааа, ну ок, проверяй, можешь ещё дополнительно сюда ссылки кинуть, я у себя добавлю - понаблюдаю

**Comment by Jeronyson** [comment]
@ElizarovEugene 
http://kinozal.tv/details.php?id=1319248
http://kinozal.tv/details.php?id=1319399

**Comment by Jeronyson** [comment]
@ElizarovEugene время все равно не отображается, если во время обновления было написано "cейчас"
 ![kinozalbug3](https://pp.vk.me/c623129/v623129035/248cb/7e79dd-NjJk.jpg)

Для фикса:
kinozal.tv.class.php, 93 строка:
```php
            $dateTime = $day.' '.$month.' '.$year.' в '.$pieces[2];
```

Нужно `$pieces[2]` заменить на `date('G:i', $timestamp)`

**Comment by ElizarovEugene** [comment]
А смотрел что он при этом в базу пишет? Какой timestamp

**Comment by Jeronyson** [comment]
@ElizarovEugene 
```php
            $timestamp = strtotime('now');
```

**Comment by ElizarovEugene** [comment]
Спасибо, я в курсе что я писал :) Я имел ввиду - в базу то правильно время пишет? те замена != на > решила проблему со сдвигом времени?

**Comment by Jeronyson** [comment]
@ElizarovEugene если в момент обновления отображалось "сейчас", то в базу он пишет время запуска скрипта.
