### ISSUE TITLE
Добавление сериала

### ISSUE THREAD

**Issue by Upitep** [ElizarovEugene/TorrentMonitor#148]
Сделать бы по-умолчанию отмеченным radiobutton Автовыбор HD 720/1080, а то иногда забываешь указать и сыпятся ошибки от php.

**Comment by psvmcc** [comment]
Кстати да, предпочитаемое для каждого трекера, к примеру запоминать последний выбранный вариант и потом сразу его подхватывать из базы, при добавлении новой закачки.

**Comment by Jeronyson** [comment]
@Upitep @psvmcc 
Также, по этому вопросу есть следующее предложение:
В форму помимо трех основных качеств добавляется выбор "Наилучшее доступное".
Алгоритм таков: при первый проверке сериала, смотрим какие качества доступны, выбираем наилучшее, которое доступно на трекере и для этого сериала впоследствии скачиваем только это качество.

То есть, если мы добавляем Arrow с Newstudio с наилучшим доступным, то при первой проверке скрипт увидит, что доступно 1080p и впоследствии будет скачиваться только 1080p. Даже если выйдет 720p, скрипт будет ждать 1080p (как если бы мы добавили сериал 1080p)

Второй случай. Если мы добавляем Arrow с Newstuidio с наилучшим доступным, но на момент проверки скрипт было доступно 400p и 720p, то впоследствии скрипт будет скачивать 720p. Даже если потом выйдет 1080p, чтобы его скачивать нужно поменять в настройке сериала на странице "Раздачи".

Жду комментариев и замечаний.

**Comment by psvmcc** [comment]
Я сильно не гонюсь за качеством, меня и 720p устраивает, к примеру на lostfilm я предпочитаю качать MP4, что бы если что залить в какой то iPad и посмотреть при случае :)
