### ISSUE TITLE
"Замыление" кода

### ISSUE THREAD

**Issue by Upitep** [ElizarovEugene/TorrentMonitor#152]
Вчера ночью сделал свежий форк проекта для последующего редактирования, но к сожалению, обнаружилось много "глюков". Предполагаю, что после большого количества свежих патчей за последнее время произошло "замыление" кода проекта. Просьба к активным тестерам скачать последнюю версию проекта и потестить основные функции ТМ'а - добавление/редактирование учетных записей трекеров, добавление/редактирования раздач и управление торрент-клиентом Transmission. Думаю, что баги лежат на поверхности и не хотелось бы лезть глубоко в логику классов :) А перед добавлением нового функционала надо бы заставить работать все старое.

**Comment by Jeronyson** [comment]
@Upitep лучше сообщите о конкретных глюках и ошибках, чтобы было понятно - что искать, потому что у меня никаких проблем нет.

**Comment by ElizarovEugene** [comment]
да, скажите какие баги, я стараюсь все тнововведения тестировать - вроде не замечал проблем

**Comment by Upitep** [comment]
Ну.. отсутствие проблем - это тоже результат. 2 замечания уже отписал вчера насчет добавления значения в поле "passkey" и некорректную отработку модуля Transmission на неправильный логин/пароль доступа к Transmission'у. Но и при правильном логин-пароле тоже закачка не добавилась в клиент - тоже были ошибки, но их отследить не успел - уснул)) Потому и попросил проверить основные функции ТМ'а на других машинах. Может быть дают сбой конкретно мои настройки и набор модулей php. Буду сегодня тестировать дальше - отпишусь по результатам.

**Comment by vlmaksime** [comment]
@Upitep у меня была проблема с добавлением в Transmission, когда я указал в настройках не правильный адрес ТМ. Сейчас все нормально добавляется

**Comment by ElizarovEugene** [comment]
@Upitep на тему что не добавляется в трансмишн - есть дебаг, просто я пока не дописал его нормальную работу и дебаг нужно включать руками в коде. если TransmissionRPC валится с эксепшаном, а не просто отдаёт ошибку - тут вопрос к нему, его переписывать я не буду точно
По поводу пасскея не готов вам ответить - только что проверил - ошибки нет, учётные данные обновляются корректно, ошибок в логе сервера нет - проверьте актуальность ваших файлов credentials.php и user-func.js

**Comment by Upitep** [comment]
C Трансмишеном сейчас разберемся, это как раз ближе к моему пониманию, т.к. код мне знаком. Про пасскей - ну нет так нет, буду наблюдать. Код актуален.

**Comment by Upitep** [comment]
С Трансмишеном разобрался - действительно, указал некорректный адрес ТМ. Теперь эту ситуацию можно отследить. А вот с пасскеем так и не понял что к чему - у вас Notice'ы в настройках php, случайно, не выключены?

**Comment by ElizarovEugene** [comment]
Да, нашёл что не так с пасскеем, только не понял почему оно у меня работало когда я тестил перед заливкой. Там ; вместо , было и он отбрасывал его

**Comment by Upitep** [comment]
Ну вот как и думал - почти все было на поверхности :) Пилим дальше...

**Comment by Upitep** [comment]
Рано закрыл - баг с пасскеем остался. Поле Passkey есть только у треке baibako - с ним все ок, но если выбрать в списке любой другой трекер, то при сохранении:
```
Notice: Undefined index: passkey in /usr/local/www/data/action.php on line 373
```
К сожалению, не силен в JS, но получается, что при выборе любого другого трекера поле passkey отсутствует и соответственно индекс passkey не передается в Database::setCredentials()?

**Comment by ElizarovEugene** [comment]
Попробуйте новый action.php

**Comment by Upitep** [comment]
Да, так-то лучше :) Может вообще не передавать passkey для всех трекеров, кроме baibako? В базе же DEFAULT NULL.

**Comment by ElizarovEugene** [comment]
Ну можно заменить в action '' на NULL :)

**Comment by Upitep** [comment]
=)))
