### ISSUE TITLE
Спрятать дополнительные настройки для торрент-клиента Deluge

### ISSUE THREAD

**Issue by Upitep** [ElizarovEugene/TorrentMonitor#155]
А вернее, раскрывать 3 поля с настройками для Transmission при выборе его в качестве торрент-клиента. Т.к. управление Deluge на данный момент не поддерживается и не имеет соответствующих настроек, то и не стоит их показывать.

**Comment by ElizarovEugene** [comment]
>Т.к. управление Deluge на данный момент не поддерживается

в каком смысле оно не поддерживается?

**Comment by Upitep** [comment]
Не корректно выразился - управление Deluge реализовано через консоль и не требуется указывать дополнительных настроек "IP, порт торрент-клиента", "Логин" и "Пароль". Стоит выделить их в отдельный слой как это сделано с опциями "Отправлять уведомления"

**Comment by ElizarovEugene** [comment]
Как это? deluge-console требует указания этих парамтеров, иначе он не подключится к серверу:
```
deluge-console "connect <host>[:<port>] <user> <password>"
```
http://dev.deluge-torrent.org/wiki/UserGuide/ThinClient

**Comment by Upitep** [comment]
Осознал глупость, извиняюсь)))
