### ISSUE TITLE
Errors::setWarnings()

### ISSUE THREAD

**Issue by Upitep** [ElizarovEugene/TorrentMonitor#156]
Не могу точно отследить баг, но при условии, что таблица "torrent" пуста и возникнет ошибка при добавлении торрента (тестил только с Трансмишеном), то в таблицу warning добавится сразу несколько одинаковых записей об этом. Т.е. если мы добавили к слежению одну тему и нажали кнопку "Запуск", то в таблицу добавится 2 одинаковых ворнинга. Если добавили сразу 2 темы и нажали "Запуск", то добавится сразу 3 ворнинга. При иных условиях, либо при последующем нажатии на "Запуск", то все отрабатывает корректно и добавляется лишь одна запись об ошибке.

Требуются дополнительные тесты, т.к. не смог найти откуда берутся лишние вызовы функции Errors::setWarnings

**Comment by ElizarovEugene** [comment]
А варнинги на одну и ту же тему?

**Comment by Upitep** [comment]
Идентичные. Тупо несколько идентичных записей. Во время поиска обнаружил, что функция Errors::setWarnings вызывается несколько раз. Через полчасика выложу скрины, чтобы было понятнее.

**Comment by Upitep** [comment]
Нашлепал разных скринов, но все не понадобились. На этих двух все видно:
http://c2n.me/3eG2Bsi
http://c2n.me/3eG2Izg

Этот "лишний" вызов setWarning вызывается из engine.php при попытке загрузить раздачу из таблицы "temp" - в этой части работает все как нужно.

Теперь вопрос в другом - почему в "temp" записалась всего 1 раздача, если торрент-файлы скачались из всех трех? Разве при неудачной попытке добавить в торрент-клиент все эти торренты не должны попасть в "temp"?

**Comment by vlmaksime** [comment]
@Upitep, а что сейчас лежит в temp?

**Comment by Upitep** [comment]
Только первая из не добавленных раздач. Пока отлаживаю дальше..

**Comment by Upitep** [comment]
Кажется, нашел причину - функция Database::saveToTemp, а конкретно $stmt->execute()  возвращает TRUE только для первого сериала из списка - для всех остальных FALSE, соответственно поэтому они и не добавляются. Проверьте, пожалуйста, этот момент на своих машинах - возможно этот косяк присутствует только на sqlite3.

**Comment by ElizarovEugene** [comment]
```
$stmt->execute() возвращает TRUE
```
оно и должно возвращать true, иначе запрос не выполнен. запрос выполняется каждый раз для каждой раздачи отдельно

**Comment by Upitep** [comment]
К примеру, в списке на добавление 3 раздачи, все должны добавиться в temp. Так вот, запрос выполняется только для первой из этого списка, для всех остальных $stsmt->execute() возвращает FALSE. Ищу пути дебага, но пока тщетно - не вижу, чтобы sqlite3 куда-нить по-умолчанию логировала запросы к БД.

**Comment by ElizarovEugene** [comment]
Ну в Database.class.php напишите в конце 929 строки var_dump($stmt); увидите запрос

**Comment by vlmaksime** [comment]
@Upitep, у меня MySQL. Обнулил все 6 раздач, в торренте прописал неправильный логин. После попытки запуска все 6 записей оказались в temp

**Comment by Upitep** [comment]
Ясно, значит, проблема только на sqlite3...
http://c2n.me/3eGkgip - запросы одинаковы, понять бы причину - почему FALSE.

**Comment by ElizarovEugene** [comment]
К сожалению, он не показывает при этом данные, которые потом биндит к запросу, по этому придётся ручками...
```
echo "INSERT INTO `temp` (`id`, `path`, `hash`, `tracker`, `message`, `date`) VALUES ($id, $path, $hash, $tracker, $message, $date)";
```

**Comment by Upitep** [comment]
Данные приведены на том же скрине :)

**Comment by ElizarovEugene** [comment]
Ну так будет сразу готовый запрос, который можно скопировать и выполнить руками в базе и посмотреть какую ошибку он выдаст

**Comment by Upitep** [comment]
согласен, минутку..

**Comment by Upitep** [comment]
http://c2n.me/3eGoCTz

Походу, нашел:
```
ERROR: UNIQUE constraint failed: temp.hash
INSERT INTO `temp` (`id`, `path`, `hash`, `tracker`, `message`, `date`) VALUES ("44", "/usr/local/www/data/torrents/[rutor.org]_420574.torrent", "", "rutor.org", "rutor.org :: НЕМИНУИМАЛ - Оставаться Живым (2015) MP3 обновлён.", "22 Мар 2015 20:08:05")
```

А теперь, смотрим схему БД:
```
Query used to create this table
CREATE TABLE `temp` ( `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `path` varchar(100) NOT NULL DEFAULT '', `hash` varchar(40) NOT NULL DEFAULT '' UNIQUE, `tracker` varchar(30) NOT NULL DEFAULT '', `message` varchar(60) NOT NULL DEFAULT '', `date` varchar(120) NOT NULL DEFAULT '' )
```
Все из-за UNIQUE поля `hash` и, действительно, такое свойство только в схеме для sqlite - в mysql отсутствует. Соответственно, добавляется первая раздача с hash=NULL, а все остальные получают отлуп т.к. hash должен быть уникален.

PS. надо бы прикрутить дебаг к sql-запросам - слишком муторно через "echo".
PSS. ушел гуглить php.. :(

**Comment by ElizarovEugene** [comment]
Интересно, а зачем я вообще хэш туда прикручивал........:)

**Comment by ElizarovEugene** [comment]
Вспомнил, это хэш предыдущей раздачи, которую надо грохать...в общем да, надо убрать просто UNIQUE для случаев когда небыло предыдущей раздачи ещё

**Comment by Upitep** [comment]
"Убрал" UNIQUE - все заработало. Фигня в том, что удалить индекс UNIQUE на "живую" скуль не дал - пришлось пересоздавать таблицу заного. Как быть с апгрейдом тем, кто уже во всю использовал sqlite (привет читателям 2gusia)? :)

**Comment by ElizarovEugene** [comment]
Да я по этому и не люблю sqlite, там "пересобрать" таблицу невозможно. Надо создавать временную таблицу, переливать данные в неё, удалять старую, создавать новую и переливать данные обратно.....

**Comment by Upitep** [comment]
Database.class.php, 24я строка:
```
$options = array(PDO::ATTR_PERSISTENT => true, PDO::ATTR_ERRMODE => PDO::ERRMODE_WARNING);
```
Вот так будет человеческим языком писать ошибку, полученную от SQL-сервера при любом выполнении запроса к БД. Правда, целесообразно только в режиме отладки, в рабочем режиме лучше PDO::ERRMODE_SILENT, чтобы не шокировать пользователя.

В конкретном случае достаточно 
```
    public static function saveToTemp($id, $path, $hash, $tracker, $message, $date)
    {
        $stmt = self::newStatement("INSERT INTO `temp` (`id`, `path`, `hash`, `tracker`, `message`, `date`) VALUES (:id, :path, :hash, :tracker, :message, :date)");
        $stmt->bindParam(':id', $id);
        $stmt->bindParam(':path', $path);
        $stmt->bindParam(':hash', $hash);
        $stmt->bindParam(':tracker', $tracker);
        $stmt->bindParam(':message', $message);
        $stmt->bindParam(':date', $date);
        if ($stmt->execute())
            return TRUE;
        else
           $stmt = NULL;
    }
```
заменить на:
```
    public static function saveToTemp($id, $path, $hash, $tracker, $message, $date)
    {
        $stmt = self::newStatement("INSERT INTO `temp` (`id`, `path`, `hash`, `tracker`, `message`, `date`) VALUES (:id, :path, :hash, :tracker, :message, :date)");
        $stmt->bindParam(':id', $id);
        $stmt->bindParam(':path', $path);
        $stmt->bindParam(':hash', $hash);
        $stmt->bindParam(':tracker', $tracker);
        $stmt->bindParam(':message', $message);
        $stmt->bindParam(':date', $date);
        if ($stmt->execute())
            return TRUE;
        else
        {
        print_r($stmt->errorInfo());
        $stmt = NULL;
        }
    }
```

**Comment by psvmcc** [comment]
@ElizarovEugene ну у каждого есть свои +/- :)
Мне к примеру нравится связка TM+SQLite, т.к. не нужно ставить дополнительные демоны(mysql/pgsql), если они уже стоят то не вопрос, но городить из-за TM, как по мне не целесообразно.

**Comment by Upitep** [comment]
@psvmcc согласен, именно для ТМ mysql как из пушки по воробьям)) Давайте поддерживать актуальность, благо PDO позволяет ;) А вот таких мест, как

```
if ($stmt->execute())
            return TRUE;
        else
           $stmt = NULL;
```
в коде, кажется еще много и надо бы это дело причесать, иначе о самом факте ошибки даже и не узнаешь, если только случайно (как вчера с таблицей warning)
