### ISSUE TITLE
Отсутствует rain.tpl.class.php

### ISSUE THREAD

**Issue by Jeronyson** [ElizarovEugene/TorrentMonitor#167]
Обновил TM до версии 1.2.1, теперь на некоторых страницах (помощь, новости, ошибки, тест) ругается на отсутсвующий файл rain.tpl.class.php в папке /class

Во время обновления ошибок не возникало, рискну предположить, что этот файл просто по ошибке не был включен в обновление 1.2.1

**Comment by Jeronyson** [comment]
![tm_121](http://funkyimg.com/i/VuxV.png)

**Comment by vlmaksime** [comment]
Эх, беда... 
Вчера @ElizarovEugene залил в репозитарий мои изменения, касающиеся шаблонов. Перекачайте полностью архив и залейте его, будет все работать.

**Comment by Jeronyson** [comment]
Вручную залил файл, теперь вылезли другие ошибки:
```
Fatal error: Uncaught exception 'RainTpl_NotFoundException' with message 'Template show_warnings not found!' in /var/www/torrent/class/rain.tpl.class.php:278 Stack trace: #0 /var/www/torrent/class/rain.tpl.class.php(171): RainTPL->check_template('show_warnings') #1 /var/www/torrent/include/show_warnings.php(92): RainTPL->draw('show_warnings') #2 {main} thrown in /var/www/torrent/class/rain.tpl.class.php on line 278
```

Ну и так далее для этих страниц

**Comment by vlmaksime** [comment]
@Jeronyson, еще папка templates нужна

**Comment by Jeronyson** [comment]
@vlmaksime да, проще будет архивом) Сейчас залью

**Comment by vlmaksime** [comment]
Думаю, что @ElizarovEugene скоро выпустит. Я вроде как шаблоны по максимуму причесал.

**Comment by Jeronyson** [comment]
@vlmaksime не смотря на то, что перезалил архивом теперь вылезает это:
```
<title><br />
<b>Notice</b>:  Undefined variable: title in <b>/var/www/torrent/cache/index.5e14f06365fd38fcc2962161f5d77170.rtpl.php</b> on line <b>5</b><br />
</title>
```

**Comment by Jeronyson** [comment]
@vlmaksime а на странице Тест....
![tm2](http://funkyimg.com/i/Vuyj.png)

**Comment by vlmaksime** [comment]
@Jeronyson, в корне должна лежать папка "cache". В ней создаются временные файлы для формирования шаблона.

**Comment by Jeronyson** [comment]
@vlmaksime она есть. И файлы там тоже есть

**Comment by vlmaksime** [comment]
Попробуйте это скрипт:
```
https://github.com/vlmaksime/raintpl/blob/master/clean_cache.php
```

**Comment by Jeronyson** [comment]
@vlmaksime кэш почистился, но ошибки по-прежнему есть

**Comment by vlmaksime** [comment]
Удалось повторить ошибку в шаблоне.
На основную работу не влияет, можете дождаться обновления или загрузить уже исправленную версию ТМ отсюда:
https://github.com/vlmaksime/TorrentMonitor/tree/new-update-page-+-templites
