### ISSUE TITLE
stable version 1.2.1

### ISSUE THREAD

**Issue by ElizarovEugene** [ElizarovEugene/TorrentMonitor#174]
И так, господа. Ввиду огромного количества жалоб на последнюю версию после мерджа исправлений от @vlmaksime я принял решение сделать откат до последней моей стабильной версии, которая должна работать корректно.

Теперь что касается обновлений: я принял такое небольшое, но важное для себя решение, что я не готов пусть процесс на самотёк, как это сейчас произошло. Я вернусь к старой схеме добавление нововведений, когда все коммиты происходили через меня вручную. Ввиду этого - большие коммиты, с переделыванием всего и вся - писать смысла нет, я просто их не осилю, да и надо ли оно?

Конечно я далёк от программиста и не все мои решения в проекте были верными и переписывать этот код можно сколько угодно раз и каждый раз находить ещё более красивое или простое/интересное решение. Я заниматься этим не буду, по крайней мере сейчас.

Да, процесс появления нового функционала будет долгим, но по крайней мере я буду уверен в том, что предлагаю людям.

Если кого то такая политики партии не устраивает - форк и вперёд :) я не против этого совершенно, но просто "сдать" проект, который я придумал и которым я занимаюсь уже больше 4 лет - я не готов, уж извините

**Comment by vlmaksime** [comment]
Что-то я не видел сообщений о проблемах. :(

**Comment by vlmaksime** [comment]
Списка проблем я так и не увидел, поэтому пошел их искать сам.

Чисто случайно набрел на проблему экранирования в show_table.php
Например если добавить вот-эту раздачу http://rutracker.org/forum/viewtopic.php?t=4939964 , то ее невозможно будет удалить из списка, пока не переименуешь.

**Comment by Upitep** [comment]
А rain.tpl.class.php с какой целью в /class остался? Ожидается ли поддержка шаблонов в будущем?

**Comment by vlmaksime** [comment]
В репозитарии @ElizarovEugene часть страниц реализована с помощью шаблонов, видимо он забыл их откатить. У меня в репозитарии можно найти актуальный релиз, в котором реализована поддержка шаблонов и Trackers.class. Сам сижу на ней, никаких проблем не наблюдаю. 
Да, в первой версии шаблона списка пользователей были некоторые проблемы, которые в данный момент поправлены. Больше никаких проблем не обнаружил.
Не пойму, почему @ElizarovEugene решил откатить мои правки :(

**Comment by ElizarovEugene** [comment]
По поводу шаблонов http://korphome.ru/TorrentMonitor/viewtopic.php?f=4&t=49

**Comment by ElizarovEugene** [comment]
@vlmaksime вы можете залить недостающие шаблоны и инклюды к ним? я попробовал руками перенести из вашей репы, но что то не взлетело

**Comment by vlmaksime** [comment]
Проблема в том, что для "add", "form", "show_table" используют Trackers.class. Возможно из-за этого и не завелось.

**Comment by ElizarovEugene** [comment]
Ну скорее всего. Тогда сам перепишу без использования Trackers.class

**Comment by Upitep** [comment]
@ElizarovEugene, а есть ли смысл городить велосипед и выдирать функционал кусками? В конечном итоге все равно плавно придем к унификации (ведь список трекеров постепенно будет дополняться). Может, разумнее будет отполировать ветку @vlmaksime и плавно перейти к этой схеме в будущем?

**Comment by ElizarovEugene** [comment]
@Upitep как я уже писал - я не вижу смысла переписывать в очередной раз движок ТМ, при том что это не несёт в общем то ничего нового в его работу.
По поводу того что список трекеров будет дополняться - за последний год по-моему ни одного нового трекера прикручено небыло, а по-моему все те, что есть сейчас - писал только я. Мне удобнее писать под тот код, который я знаю, нежели сначала принять достаточно глобальные изменения в "ядре", которые мне нужно будет изучить и запомнить и ориентироваться уже под них. Лучше я буду тратить время на доработку функционала, исправление багов и тд, чем изучать чужой код.
С шаблонами да - согласен, вещь нужная и я сам о ней думал, и мне уже предлагали разные шаблоны потом нарисовать хотя бы в разных цветовых гаммах.

**Comment by Upitep** [comment]
Согласен, есть резон :) Про шаблоны даже обсуждать смысла нет - любой шаг в сторону в части дизайна для дизайнера, не задействованного в проекте будет очень тяжелым, да и сама по себе концепция отделения "мух от котлет" уже давно стала хорошим тоном :)

**Comment by ElizarovEugene** [comment]
@Upitep по поводу дизайна я так скажу - были люди, которые говорили о том, что плохо что html от логики у меня не отделён, не удобно шаблоны рисовать. На предложение - нарисовать шаблон, который я сам сверстаю - мне никто не ответил...так что не сильно уверен что это станет толчком к их появлению, пока я опять-таки сам за это не возьмусь, заплатив денег дизайнеру :)

**Comment by Upitep** [comment]
Ну я примерно в этом контексте и говорил))) К дизайну имею очень посредственное отношение, да и то уже все забыто со времен институтской скамьи (ну под собственные учебные проекты верстал, баловство), посему и помочь в этой теме не смогу)

**Comment by ElizarovEugene** [comment]
@vlmaksime вы https://github.com/justindomingue/ohSnap его же использовали? у меня что то уведомления друг на друга накладываются и всё

**Comment by vlmaksime** [comment]
@ElizarovEugene , его. Там с CSS какая-то беда. Когда я вручную код вставлял, то они накладывались. Я Выдрал файл CSS из примера, тогда они стали в стек падать.

**Comment by ElizarovEugene** [comment]
@vlmaksime ага, спасибо, так заработало

**Comment by vlmaksime** [comment]
Ничего сверхъестественного в коде я не делал. В модулях поубирал проверки на имя треккера, вместо этого я разделил классы треккеров на 3 типа 
* threme - классы для работы с торрент-треккерами, которые реализованы в виде форумов. rutracker и все остальные
* search - классы, которые отвечают за поиск раздач пользователей
* series - классы для работы треккерами типа LostFilm, где раздача ищется по названию в ленте RSS
Почти везде, где понял смысл кода, я эти привязки к названиям сайтов переделал на привязку к типу треккера.
В классах треккеров изменил способ передачи входных параметров процедуры main. Вместо кучи входных параметров, которые отличаются для разных типов классов, я передаю один параметр (массив всех доступных значений параметров) и уже его извлекаю.
В классы треккеров были добавлены функции:
* generateURL - для генерации ссылки на раздачу, является не обязательной. Если ее нет, то ссылка не генерируется
* getThreme - для определения id раздачи. Я заметил, что алгоритм выделения id общий для большинства треккеров, поэтому эта функция не обязательна. Нужна только для тех классов, которые используют уникальний алгоритм получения id.
* getTrackerType - возвращает тип треккера. Тоже не обязательна. Если отсутствует в классе, то будет возвращет тип "threme".

В классе Trackers.class вроде как детально описал назначение процедур и функций.
