### ISSUE TITLE
varchar(30) - Маловато будет! ©

### ISSUE THREAD

**Issue by Shooshka** [ElizarovEugene/TorrentMonitor#176]
Сабж, параноики негодуют, пароли режутся! :)

**Comment by vlmaksime** [comment]
Дык а сколько надо то?
100, 200, 1000?

**Comment by Shooshka** [comment]
Ну я себе поставил нужную мне длинну, я собсна к чему данную issue создал - вполне вероятно, что кто-то тоже наткнётся на непонятки, когда с какого-либо менеджера паролей копипастишь пасс, жмакаешь сохранить, а в базке он режется до 30 символов... и сидишь ищешь проблему :)

Имхо 255 как для кук и пасскея по дефолту норм было бы.
