### ISSUE TITLE
Обновлять заголовок автоматически

### ISSUE THREAD

**Issue by Shooshka** [ElizarovEugene/TorrentMonitor#177]
Добавить опциональную галку "Обновлять заголовок автоматически" при добавлении раздачи, а не только в списке раздач при редактировании оной.

**Comment by ElizarovEugene** [comment]
Да, вчера только обсуждали, добавлю в расширенные настройки

**Comment by Shooshka** [comment]
Ну я так, в качестве напоминалки, а то обсуждали же ещё и примерно месяц назад :)))

**Comment by ElizarovEugene** [comment]
угу, я и забыл :)

**Comment by Shooshka** [comment]
Done in 1.2.2
