### ISSUE TITLE
Отправка уведомлений

### ISSUE THREAD

**Issue by gelato** [ElizarovEugene/TorrentMonitor#180]
Привет. Хотел бы сообщить, что скрипт не может отправлять уведомления на адреса типа: "5400bbf0-4731-ecc6-b52c-e484e744d283+79781111111@sms.ru" тогда как на обычные адреса отправляет нормально.

Ну и кстати, еще - хотел бы поблагодарить за great piece of software :)

**Comment by ElizarovEugene** [comment]
Приветствую. А что говорит, на что ругается? Скрипт то сам ничего не отправляет, это делает функция mail() в PHP.

**Comment by gelato** [comment]
Да ничего не говорит и не ругается в свои логи - просто не отправляет на этот адрес ничего, когда на обычный почтовый адрес все шлет. Может в плюс-адресации дело, или в слишком длинном адресе? Сам же адрес - просто странноватый вид автоматического почтовика sms.ru, отправляющего смс-ки.

**Comment by ElizarovEugene** [comment]
вы логи веб-сервера посмотрите

**Comment by gelato** [comment]
Простите, забыл сказать сразу - там тоже ничего нет.
Вот думаю - может в самом мыле проблема... С консоли принимает сообщения и отправляет смс-ки, а я вот пытался перенаправление настроить в фильтрах почты - сообщение с кодом подтверждение не приходит.

**Comment by ElizarovEugene** [comment]
а логи почтовика смотрели?
я сейчас отправил вас 3 сообщения, 2 из них из PHP. почтовик ошибок не видит - письмо уходит:
```
Apr 12 22:13:25 nginx postfix/smtp[31739]: 2947E20B1F69: to=<5400bbf0-4731-ecc6-b52c-e484e744d283+79781111111@sms.ru>, relay=smtp.sms.ru[89.188.102.66]:25, delay=0.29, delays=0.11/0.02/0.08/0.07, dsn=2.0.0, status=sent (250 OK)
```

**Comment by gelato** [comment]
Да у меня постфикс через гугл в рилее... То что на указанный мной адрес матов не поступает доказывает лишь что почтовик там странный - адрес-то неверный. Сейчас форвардинг настрою и посмотрю что это даст.

**Comment by gelato** [comment]
Нет, смотрите, а через форвардинг отправляет нормально - я фильтром заставляю другой гмэйловский ящик уже отправлять на смс-почту.
