### ISSUE TITLE
Роскомнадзор и kinozal.tv

### ISSUE THREAD

**Issue by schild7000** [ElizarovEugene/TorrentMonitor#181]
Проблема (больше конечно радость) в том что Роскомнадзор полностью не блокирует kinozal.tv для нашей страны, но на страницах появляются надписи: "Раздача заблокирована Роскомнадзором. Раздача заблокирована на территории России по требованию Роскомнадзора."
![2015-04-13 12-15-27](https://cloud.githubusercontent.com/assets/10937225/7112872/dc2855b6-e1d6-11e4-8900-459e051aaccd.png)
ТМ соответственно скачать такую раздачу не может а в ошибки пишет: "Transmission Не удалось получить данные torrent-файла."

Может в таких случаях предусматреть возможность скачивать раздачи использую magnet ссылки, т.е. брать хеш со страницы вида: http://kinozal.tv/get_srv_details.php?id=ID_РАЗДАЧИ&action=2 (например http://kinozal.tv/get_srv_details.php?id=1331803&action=2) и дописав впереди magnet:?xt=urn:btih: послать её в torrent-клиент.

Тут сразу скажут что есть еще несколько режимов работы ТМ такие как работа в режиме сохранения торрент-файлов и RSS ленты но тут конечно тоже нужно что то делать... возможно даже mirror-kinozal.tv поднимать )))

**Comment by ElizarovEugene** [comment]
>mirror-kinozal.tv 

это точно - НЕТ! :)))
Решение вышеописанной проблемы, будет немного позже, когда я прикручу ошибки по аналогичным проблемам на rutracker.org https://github.com/ElizarovEugene/TorrentMonitor/issues/129

**Comment by schild7000** [comment]
Ну этоже получится частичное решение... просто информирование о закрытии раздачи... получается если я в РФ то скачать так и не не получится (((

**Comment by ElizarovEugene** [comment]
А что вы от меня хотите то? Что бы я научил TransmissionRPC.class.php или deluge-console понимать магниты? + как вы верно заметили
>Тут сразу скажут что есть еще несколько режимов работы ТМ такие как работа в режиме сохранения торрент-файлов и RSS ленты

так что я тут других каких то решений просто не вижу

**Comment by vlmaksime** [comment]
@ElizarovEugene я на днях гуглил альтернативы текущему Transmission.class и заметил, что в одном из классов через метод add передавали не ссылку на *.torrent файл, а бинарное значение файла в формате base64. Надо бы попробовать такой вариант передачи данных для текущего класса, может и проканает. Тогда настройку с адресом сайта можно будет сделать обязательной для deluge.
Ну а магнеты он должны приниматься без проблем, как и url ссылка.

**Comment by ElizarovEugene** [comment]
1. magnet:?xt=urn:btih:kinozal.tv/get_srv_details.php?id=1331803&action=2 у меня не работает
2. нет, я уже говорил - логика работы будет для обоих торрент-клиентов одинакова + то что касается rss и сохранения файлов

**Comment by vlmaksime** [comment]
1. Магнет ссылка не правильная.
Необходимо получить содержимое адреса "kinozal.tv/get_srv_details.php?id=1331803&action=2", здесь получим следующее содержимое
```    Инфо хеш: BB5C75BED6D96419C3D70F97AE954F497FA6780A
    Размер части торрента: 2 МБ
    GOT (S05) DUB 720p
        Subs Rus
            Game.of.Thrones.S05E01.HDTV.720p.DUB.[qqss44].srt 53 КБ (54426)
        Game.of.Thrones.S05E01.HDTV.720p.DUB.[qqss44].mkv 1.06 ГБ (1141147360) ```
Нас интересует 1 и 3 строки. Из первой строки берем значение ХЭШа, из 3й название раздачи. Генерируем магнет вида:
magnet:?xt=urn:btih:BB5C75BED6D96419C3D70F97AE954F497FA6780A&dn=GOT (S05) DUB 720p&tr=http://tr1.kinozal.tv/announce.php?passkey=*тут подставить свой passkey*&tr=http://retracker.local/announce

Ссылка через GUI ссылка благополучно добавилась и стала на закачку. 

2. Можно всю логику перенести в отдельный класс, а все нюансы перенести в классы клиентов. Например зачем для Transmission заморачиваться с передачей ссылок на треккер, если ему можно передать бинарное значение файла, тем самым убрав привязку к адресу ТМ. 
Не понимаю, зачем не использовать те возможности Transmission, которых повышают удобство использования только из-за того, что их нет в Deluge?

**Comment by ElizarovEugene** [comment]
1. Опять-таки - реализация только для одного из всей кучи трекеров?
2. По тому что у приложения должна быть логика! работы. Нельзя на каждом углу делать так, как можно там, а на других по другому. Просто вы не сталкиваетесь с поддержкой ТМ, не пишите инструкции и не отвечаете на вопросы "а как...", "а почему..." и тд

**Comment by vlmaksime** [comment]
1. И тут опять сталкиваемся с проблемой унификации. Например при использовании Trackers.class не составит труда в классе kinozal.tv прописать отдельное правило для генерирования ссылки на раздачу. Опишу принцип:
1. В классе kinozal.tv описываем функцию getMagnetURL, которая формирует ссылку на магнет
2. В самом Trackers.class описываем функцию getTorrentURL. В функции проверяем наличие в классе функции getMagnetURL. Если функция есть, вызываем ее и получаем magnet ссылку, если ее нет, то генерируем ссылку на торрент файл, который лежит в папке torrents.
3. Ссылку, полученную в результате выполнения Trackers::getTorrentURL(params) передаем в торрент-клиент

**Comment by ElizarovEugene** [comment]
@vlmaksime как вы магнет будете превращать в файл для раздачи в RSS?

**Comment by vlmaksime** [comment]
Ну тут 2 варианта. 
1. Использовать ТМ только в связке с торрент-клиентом
2. В папке torrents создавать файлы с типом *.magnet и в них сохранять ссылку. При формировании RSS ленты в качестве ссылки выводить содержимое *.magnet файла.

**Comment by cisco2** [comment]
Для чего делали работу через socks прокси ? Пускать TM через tor с нероссийским ip и будет всем счастье - обычные ссылки на скачивание будут доступны.

**Comment by schild7000** [comment]
@cisco2 Когда-то (для меня лично) было отличное решение но сейчас через TOR однозначно не работает "lostfilm.tv", также сейчас попробовал пишит что и "baibako.tv" не доступен. @ElizarovEugene говорит: "По тому что у приложения должна быть логика! работы." это да... но обычно как хотим так не получается т.к. все трекеры и провайдеры разные и у каждых свои проблемы... соответственно необходимы отдельные решения для каждой проблемы хоть это и кажется "костылями" и идет против логики.

**Comment by cisco2** [comment]
@schild7000 , ЕМНИП бабайка-тв наоборот - блокирует европейские адреса :-). Пробуй ставить украинские или белорусские :-)

**Comment by psvmcc** [comment]
Все нормально у baibako с европейских IP.

**Comment by schild7000** [comment]
У меня в настройках TOR стоит ExcludeNodes {RU},{UA},{BY}

**Comment by schild7000** [comment]
Так как раздачи блокирует сам kinozal.tv, а не роскомнадзор, принимая решение ограничивать доступ к части контента пользователям из России чтобы не попадать в реестр то решилось всё просто... пошел на nnm-club.me и добавил раздачу с него. Просто забыл что не принципиально с какого трекера качать т.к. всё равно будет хранится весь сериал (это я сейчас конкретно про Игру престолов в озвучке Кравец и подобных которые нельзя скачать по одной серии как с лоста и байбако).

Действительно необходимо решить проблемы с rutracker.org #129 и применив подобное решение для других... переходить на более "бесстрашные" трекеры ))))

**Comment by schild7000** [comment]
Теперь и LostFilm начал блокировать для наших пользователей...
![2015-04-16 08-25-47](https://cloud.githubusercontent.com/assets/10937225/7174557/b0fa8bd2-e412-11e4-81d6-e7648a04ca06.png)

хорошо что lostfilm-mirror появился )))

**Comment by vlmaksime** [comment]
А как выглядит RSS лента с игрой пристолов для россии?

**Comment by schild7000** [comment]
Сейчас немогу посмотреть т.к. на данное время игра пристолов уже не входит в ленту (там по 15 пунктов в ленте)

**Comment by Upitep** [comment]
Ппц, такого поворота я не ожидал))) Почти доделал систему автоматического проксирования заблокированных ресурсов (по спискам antizapret.prostovpn.org), а тут вон ход конем от них)) Если ресурс не заблочен, то и прокся не сработает.. Не знаю даже - нужна ли такая система для российских пользователей или теперь каждый трекер будет такие финты мутить...

**Comment by vlmaksime** [comment]
@Upitep, походу доработка уже не актуально :)
Ну два треккера с такой фишкой уже появились, посмотрим как поведут себя остальные треккеры.
Я ж правильно понимаю, что закрываются не все раздачи, а выборочно?

**Comment by Upitep** [comment]
Да, только "проблемные". И насколько я понял - пока только "Игра престолов", как самый кассовый. Сейчас у нас в рекламе очень пиарят Амедиа и Игру престолов, та же пиццерия Папа Джонс или Билайн смсками... бред, в общем))

**Comment by psvmcc** [comment]
Да просто как раз Amedia имеет права на трансляцию GoT на територии РФ. 
Ну а что бы не блочили полностью сайт для РФ, lostfilm поступил таки более правильно, и решил блокировать раздачи. Это имхо самое лучшее решение, в связи с копирайтами.

**Comment by cisco2** [comment]
Админы стоят перед выбором - или закрывать отдельные раздачи слишком говнистых копирастов или роскомнадзор даст команду закрыть весь форум-трекер... Кто-то удаляет такие раздачи как на тру, кто-то блокирует скачивание с российских ip + еще некоторые провайдеры со страху без приказа роскомнадзора (на всякий случай - чтоб не попасть под раздачу) сами все блокируют. Короче полный дурдом...

**Comment by Upitep** [comment]
Тем не менее, проксирование допилил и отладил - осталось дождаться пока Евгений перезальет репозиторий ТМ, чтобы сделать коммит и наблюдать за развитием ситуации - может быть еще какой трекер заблочат..

**Comment by cisco2** [comment]
@schild7000, надо открывать опять эту закрытую иссую раз такая фигня...

**Comment by cisco2** [comment]
https://github.com/ElizarovEugene/TorrentMonitor/commit/8e1716bc1c0617cef33484a610a164261014fd3d#commitcomment-10781887
 :-(

**Comment by Upitep** [comment]
https://github.com/vlmaksime/TorrentMonitor/pull/1
