### ISSUE TITLE
Расширить возможность работы через socks прокси

### ISSUE THREAD

**Issue by cisco2** [ElizarovEugene/TorrentMonitor#182]
Предложение такое (сам ни разу не программер - неосилю): сделать настройку работы через прокси для каждого трекера отдельно. Т.е. сейчас реализовано как - ставим галку, вводим ip:порт и все трекеры начинают опрашиваться TM-ом через прокси. 
В принципе спасает, но все-таки tor медленная схема и ради одного заблоченного трекера тормозить остальные - не комильфо. Плюс народ жалуется, что через tor не работают лостфильм и байбако.тв. Плюс на некоторых трекерах админы взяли моду ставить запрет скачивания с российских ip раздач, не нравящихся роскомнадзору (чтобы эти нехорошие люди не заблочили вообще весь форум).
Предлагаю сделать возможность работы через прокси не для всех разом, а для каждого трекера индивидуально. 
Как вариант можно включать работу через прокси не для трекеров, а для определенных раздач устанавливать признак работы через прокси. Может даже и так потому что на многих трекерах админы блокируют только определенные раздачи.

**Comment by ElizarovEugene** [comment]
Да мы это уже обсуждали :) https://github.com/ElizarovEugene/TorrentMonitor/pull/159
Вот просто представь: на данный момент у нас 15 трекеров, соответственно это 15 полей настроек! У нас народ и так в них путается, а тут вообще будет зверская портянка, да собственно и зачем? TM не подразумевался как система работающая в риалтайме и по сути не сильно принципиально - 2 минуты скрипт будет работать или 5, это в общем то ничего не меняет. У меня есть люди, кто юзает ТМ в промышленных масштабах и у них такая вот портянка http://take.ms/A9PBQ
и ничего, меньше чем за 2 минуты отрабатывает :) ну а с учётом тора это будет ну 4 минуты...в общем ничего такого в скорости тут нет

**Comment by cisco2** [comment]
Да, выставлять проксю для каждой раздачи таким борцам за свободу как серпом по пальцам....
Re: на данный момент у нас 15 трекеров, соответственно это 15 полей настроек! 
Совместить с "учетными данными" ? Выбираешь трекер, поля логина и пароля не трогаешь, галку "работать через прокси" для этого трекера ставишь, жмешь "сохранить". И в базе признак работы через проксю можно в таблице логинов хранить - хоть и не совсем credentials , но влияет сильно.

**Comment by Upitep** [comment]
Решение должно быть максимально универсальным. Вы знаете открытые прокси, которые позволят нам работать со всеми трекерами? TOR, как оказалось, не панацея - т.к. cloudflare его легко детектит и вываливает анти-бот капчу, чтобы обойти которую надо писать целый браузер и подтягивать ocr и т.д. и т.п. - бред. Как вариант, я сейчас обдумываю реализацию функции, которая будет сверяться с реестром и пускать трафик через antizapret.prostovpn на заблокированные ресурсы. Но, блин, опять панацеи не выходит, если наши свободоборские трекеры уже начали блочить раздачи для российских IP.

В пору подымать отдельный VPN для проекта и пускать все запросы к трекерам через него :(

**Comment by cisco2** [comment]
Еще как вариант на обсуждение: В credentials хранить не признак работы с прокси, а само значение ip:порт прокси для этого трекера. Т.е. можно будет реализовать работу через разные tor прокси (ходить на определенные трекера с ip подходящей страны). От cloudflare, конечно не спасет...

**Comment by ElizarovEugene** [comment]
@cisco2 ну у большинства юзеров логика точно не сработает что в разделе учётных данных будут ещё и настройки прокси для этого трекера :)

**Comment by vlmaksime** [comment]
@ElizarovEugene, можно хранить их в таблице credentials, а выводить для заполнения на странице настроек. Юзер даже и не узнает, что они храняться в одной таблице.
Может все же стоит подождать @ZeBriD, он там разрабатывает механизм хранения настроек модулей в отдельной таблице. Можно будет Прикрутиться к ней, чтоб не плодить новые поля в таблице credentials.

**Comment by ElizarovEugene** [comment]
@vlmaksime вот на самом деле - как хранить, это как раз совершенно пофигу. хоть отдельный таблица для каждой настройки :)) главное - как это удобно и лаконично дать пользователю, что бы это было удобно и понятно без дополнительного мануала. когда я говорю об общей логике - я имею ввиду именно это. как оно там "под капотом" работает - пользователь не знает и ему пофигу, а вот как оно выглядит - для него важно в плане понимания. ну и я здесь же допишу про то что мы уже с магнетами обсуждали, что б 2 раза не вставать: вот у нас есть функция у ТМ - сохранения торрента в файл и рсс лента. Ну не можем мы конкретно для одного трекера сделать работу с магнетами. Даже если мы их в файл будет сохранять: это не верно, по тому что это не torrent-файл. Вот если бы для всех трекеров можно было качать по магнету - можно было бы реализовать как ещё один вариант работы ТМ с клиентами, а так, к сожалению - нет

**Comment by cisco2** [comment]
@ElizarovEugene , для придания пущей логичности - в веб интерфейсе ТМ переименовать страницу "Учетные данные" в "Настройки трекеров", а "Настройки" - в "Общие настройки". И тогда такое размещение будет понятным.
Тем более не забывайте, что подавляющая часть пользователей ТМ - это все-таки advansed users.

**Comment by ElizarovEugene** [comment]
>подавляющая часть пользователей ТМ - это все-таки advansed users

вот честно - такой статистики у меня конечно же нет, но я с этим утверждением не соглашусь. да и даже если их будет всего 10 человек и каждый из них мне раз в неделю будет задавать вопрос "а как..." - для меня это много :)
вот ситуацию расскажу, только недавно была:
встаю я с утра, читаю почту, письмо от Васи В часов в 5 утра "здрасьте, поставил ТМ, не работает, выдаёт ошибку Х", часов в 7 утра второе письмо "А, всё, разобрался, работает".
Такая ситуация была два раза - на прошлой и позапрошлой неделе от разных людей :) В наше время - уровень современных, так называемых "advansed users" - крайне низкий. Все действительно advansed users - сидят тут и либо коммитят, либо вносят предложения...вот сколько нас тут - человек 20? :)
