### ISSUE TITLE
 version 1.2.2 

### ISSUE THREAD

**Issue by vlmaksime** [ElizarovEugene/TorrentMonitor#184]
Пока репозитарий находится в забвении, выскажу пару замечаний по релизу.
1.Справка перенесена в xml, что стало удобнее. Предлагаю немного переделать этот механизм. Сейчас перечень разделов перечислен в коде
```
    //Помощь
    $contents[] = array( 'title' => 'Помощь', 'content' => $xml->help,);
    //О проекте
    $contents[] = array( 'title' => 'О проекте', 'content' => $xml->about,);
    //Разработчики
    $contents[] = array( 'title' => 'Разработчики', 'content' => $xml->developers,);
```

Возможно лучше будет перенести их в тело xml файла? Cделать структуру:

```
раздел
    Заголовок - Помощь
    Содержимое
/раздел
раздел
    Заголовок - О проекте
    Содержимое
/раздел
```

Это упростит добавление новых разделов справки в будущем

2.Макеты шаблонов лежат в корне папки templates, что не есть хорошо. У себя я их перенес в папку templates/default, благодаря этому с легкостью можно реализовать механизм переключения шаблонов. У нас уже есть все необходимое для этого. Достаточно будет добавить в настройки параметр с выбранным шаблоном, а функцию ```Sys::getTemplateDir()``` переделать, чтоб возвращала путь к выбранному шаблону. А все новые шаблоны будут ложиться в каталог templates

**Comment by Shooshka** [comment]
А параноики бампают - https://github.com/ElizarovEugene/TorrentMonitor/issues/176

ПС. Касаемо 1.2.2 - зеркало лоста протестил, всё отлично. Базку правил руками, данные туда забивал тоже руками, после этого только решил проверить как оно в веб-морде, а там настроек-то и нет:

![screen](http://ishoo.ru/pic/pic-16042015-164945.png)

**Comment by vlmaksime** [comment]
3.Судя по коду action.php, на странице авторизации была добавлена галочка "Запоминать", но в макете эта галочка не добавлена и в JS нет ее обработки

**Comment by vlmaksime** [comment]
4. На странице добавления раздач появилась галочка "Обновлять заголовок автоматически", но при добавлении раздачи она не сохраняется.
