### ISSUE TITLE
Раздачи lostfilm.tv в lostfilm-mirror

### ISSUE THREAD

**Issue by schild7000** [ElizarovEugene/TorrentMonitor#185]
Так как на сегодня помимо зеркала lostfilm-mirror остается и оригинальный lostfilm.tv для удобства и быстроты перехода на зеркало (а может и наоборот) предлагаю что бы не передобавять раздачи с lostfilm.tv на lostfilm-mirror добавить кнопку "Перенести раздачи lostfilm.tv в lostfilm-mirror" в настройках lostfilm-mirror (у оригинального можно наоборот вдруг захочется вернутся).

Если добавлять такие кнопки, логичнее будет переименовать "Учётные данные" в "Настройки трекеров" т.к. уже сейчас у baibako.tv есть поле Passkey что не совсем логично (на мой взгляд).

![2015-04-16 18-35-21](https://cloud.githubusercontent.com/assets/10937225/7185405/1948c5e8-e46b-11e4-81f4-1a128782b8fd.png)

**Comment by vlmaksime** [comment]
А может переделать, чтоб зеркало использовалось не явно?
Например сделать класс "lostfilm.tv.mirror.php" вместо "lostfilm-mirror.engine.php". А в настройках треккера добавить флаг "Использовать зеркало". А в "lostfilm.tv.engine.php" добавить проверку, мол если с оригинала не удалось загрузить, то загружать с зеркала.

**Comment by schild7000** [comment]
@vlmaksime согласен что нужно скрыть от обычных пользователей как я уже писал в #159 можно добавить в настройки лоста галку "Использовать зеркало mirror-lostfilm.tv" которая по умолчанию будет стоять для уменьшения вопросов от простых пользователей так везде будет написано lostfilm.tv а что там под капотом знать всем необязательно )))
Я думаю сейчас обычный пользователь будет думать что такое lostfilm-mirror и будет пытаться добавлять раздачи в лост и опять задавать вопросы почему это не работает.
