### ISSUE TITLE
Использование дерева папок при выборе каталога

### ISSUE THREAD

**Issue by vlmaksime** [ElizarovEugene/TorrentMonitor#186]
Нашел интересный модуль: https://github.com/daverogers/jQueryFileTree , пример использования можно посмотреть здесь: http://labs.abeautifulsite.net/archived/jquery-fileTree/demo/

Рядом с полем ввода каталога загрузки раздачи можно добавить кнопку "Обзор", по нажатию на которую будет открываться дерево каталогов и пользователь сможет выбрать каталог.

Для работы модуля требуется указать корневой каталог, в котором он будет искать файлы. По умолчанию можно сделать "/mnt", но этот путь может быть не для всех удобным. Например для меня удобнее использовать в качестве корневого каталога "/mnt/HD/HD_a2/", а если сервер работает под Windows, то путь "/mnt" работает работать не будет. Предлагаю этот параметр вынести в настройки ТМ.

Если @ElizarovEugene не против, то я займусь реализацией.

UDP: В нем нет возможности добавления каталогов :(
Можно будет допилить в этот плагин такую возможность или найти другой плагин с такой возможностью

**Comment by ElizarovEugene** [comment]
да мне кажется нет особого смысла, учитывая что root всё-равно придётся указывать отдельно, да и не у всех торрент-клиент стоит на той же машине что и ТМ

**Comment by ElizarovEugene** [comment]
посмотри ещё - это штука директории создавать так же не умеет, значит или их предварительно надо руками создавать - что не придаёт этому делу юзабилити.
а если вы раскидываете раздачи по уже имеющимся директориям постоянно - так есть автокомплит для путей

**Comment by vlmaksime** [comment]
Я упоминал это в первом посте. Ну научить его создавать каталоги не сложно.
Изначально я наткнулся на этот модуль в своем NASe, на нем он умеет создавать каталоги, можно будет подсмотреть код создания каталога в нем.
Или, как я говорил в первом посте, можно поискать другой плагин, в котором уже есть возможность создания каталогов.

**Comment by ElizarovEugene** [comment]
только если он адекватно кросплатформенный и при этом не требует дополнительных отдельных настроек

**Comment by cisco2** [comment]
Коль пошла такая пьянка посмотрите уж тогда
http://extplorer.sourceforge.net/
Есть еще такая самоделка на php (может пригодится как база - там и файловый менеджер и редактор)
http://forum.zyxmon.org/topic408-dopolnitelnye-vozmozhnosti-vebinterfeisa-php-versiya.html
К rutorrent-у есть плагин обзора папок getdir
https://code.google.com/p/rutorrent/wiki/Plugin_getdir?wl=ru

**Comment by ElizarovEugene** [comment]
@cisco2 ну это точно уж очень громоздкое решение

**Comment by schild7000** [comment]
Можно проще и на мой взгляд удобнее... взять и переносить путь из пункта "Директория для скачивания" из общих настроек...

![2015-04-17 16-09-20](https://cloud.githubusercontent.com/assets/10937225/7202608/aaa7fbe2-e51c-11e4-97c5-9b3c5a5c67e1.png)

в пункт "Директория для скачивания" в дополнительных настройках при добавлении раздачи и в такой же пункт при редактировании раздач...

![2015-04-17 16-12-57](https://cloud.githubusercontent.com/assets/10937225/7202613/af140860-e51c-11e4-87e3-eaff609e0292.png)

так как уверен что у большинства все раздачи хранятся примерно в одном месте (недалеко от папки по умолчанию) добавляется только папка имя которой проще дописать к уже имеющемуся например /mnt/Public/Downloads/ чем выбирать обзор -> найти нужную папку -> потом выбирать создать папку и всё равно писать имя этой папки... ведь если дописать к пути имя папки которой нет торрент клиент её всё равно создаст.

**Comment by vlmaksime** [comment]
@schild7000, хорошая мысля. А для раздач с сериалами можно автоматически склеивать путь по умолчанию и название сериала.

Я тут еще один скрипт нашел, этот будет более функциональный: http://www.jstree.com/
