### ISSUE TITLE
Не проходит функция checkConfig при пустом пароле

### ISSUE THREAD

**Issue by andreymukha** [ElizarovEugene/TorrentMonitor#187]
Я так понимаю, что скрипт предназначен больше для локального использования, а раз так, то много у кого может не быть пароля к юзеру базы данных, особенно актуально для пользователей винды (open-server, denwer...)

**Comment by ElizarovEugene** [comment]
за все 4 года существования ТМ, вопрос о пустом пароле поднимался лишь один раз, и здесь я был непреклонен - отсутствие пароля у БД это не по феншую

**Comment by andreymukha** [comment]
Смотрите сами, я просто предложил... А вообще это достаточно нормальная практика во многих CMS (так же таких популярных, как Drupal) не проверять заполненность пароля к базе

**Comment by ElizarovEugene** [comment]
у меня там наипростейшая функция проверки настроек
на самом деле - поставьте просто пробел в пароле и это должно решить проблему

**Comment by andreymukha** [comment]
Да я, в принципе, обошёл это, я так просто написал, на будущее. Был удивлён, что тут пароль проверяется, хотя ранее такого не встречал))
