### ISSUE TITLE
Ошибка: Не могу получить доступ к трекеру

### ISSUE THREAD

**Issue by c4uran** [ElizarovEugene/TorrentMonitor#189]
(версия 1.2.7)
28 Авг 2015 10:02	  nnm-club.me	  Не могу получить доступ к трекеру.
28 Авг 2015 10:02	  rutor.org	  Не могу получить доступ к трекеру.

при этом все тесты проходит на ура, у меня одного такое или что-то поломалось?

**Comment by ElizarovEugene** [comment]
проверил рутор - вроде всё ок

**Comment by c4uran** [comment]
а что у меня может быть не так?

результаты теста:

Основные настройки
Подключение к интернету установлено.
Конфигурационный файл существует и заполнен.
Расширение cURL установлено.
Запись в директорию для torrent-файлов /volume1/web/torrentmonitor/torrents/ разрешена.
Запись в системную директорию /volume1/web/torrentmonitor/ разрешена.
Основной файл для работы с трекером anidub.com найден.
Учётные данные для работы с трекером anidub.com не найдены.
Трекер anidub.com доступен.
Основной файл для работы с трекером animelayer.ru найден.
Учётные данные для работы с трекером animelayer.ru не найдены.
Трекер animelayer.ru доступен.
Основной файл для работы с трекером baibako.tv найден.
Учётные данные для работы с трекером baibako.tv не найдены.
Трекер baibako.tv доступен.
Основной файл для работы с трекером casstudio.tv найден.
Учётные данные для работы с трекером casstudio.tv не найдены.
Трекер casstudio.tv доступен.
Основной файл для работы с трекером hamsterstudio.org найден.
Учётные данные для работы с трекером hamsterstudio.org найдены.
Трекер hamsterstudio.org доступен.
Основной файл для работы с трекером kinozal.tv найден.
Учётные данные для работы с трекером kinozal.tv не найдены.
Трекер kinozal.tv доступен.
Основной файл для работы с трекером lostfilm-mirror найден.
Учётные данные для работы с трекером lostfilm-mirror не требуются.
Трекер lostfilm-mirror доступен.
Основной файл для работы с трекером lostfilm.tv найден.
Учётные данные для работы с трекером lostfilm.tv не найдены.
Трекер lostfilm.tv доступен.
Основной файл для работы с трекером newstudio.tv найден.
Учётные данные для работы с трекером newstudio.tv найдены.
Трекер newstudio.tv доступен.
Основной файл для работы с трекером nnm-club.me найден.
Дополнительный файл для работы с трекером nnm-club.me найден.
Учётные данные для работы с трекером nnm-club.me найдены.
Трекер nnm-club.me доступен.
Основной файл для работы с трекером novafilm.tv найден.
Учётные данные для работы с трекером novafilm.tv не найдены.
Трекер novafilm.tv доступен.
Основной файл для работы с трекером pornolab.net найден.
Дополнительный файл для работы с трекером pornolab.net найден.
Учётные данные для работы с трекером pornolab.net найдены.
Трекер pornolab.net доступен.
Основной файл для работы с трекером rustorka.com найден.
Учётные данные для работы с трекером rustorka.com не найдены.
Трекер rustorka.com доступен.
Основной файл для работы с трекером rutor.org найден.
Учётные данные для работы с трекером rutor.org не требуются.
Трекер rutor.org доступен.
Основной файл для работы с трекером rutracker.org найден.
Дополнительный файл для работы с трекером rutracker.org найден.
Учётные данные для работы с трекером rutracker.org найдены.
Трекер rutracker.org доступен.
Основной файл для работы с трекером tfile.me найден.
Дополнительный файл для работы с трекером tfile.me найден.
Учётные данные для работы с трекером tfile.me не требуются.
Трекер tfile.me доступен.
Основной файл для работы с трекером tracker.0day.kiev.ua найден.
Учётные данные для работы с трекером tracker.0day.kiev.ua не найдены.
Трекер tracker.0day.kiev.ua доступен.
Основной файл для работы с трекером tv.mekc.info найден.
Учётные данные для работы с трекером tv.mekc.info найдены.
Трекер tv.mekc.info доступен.

**Comment by ElizarovEugene** [comment]
из консоли запустите, предварительно проверив учётные данные

**Comment by c4uran** [comment]
простите а что запустить? тест? есть краткая инструкция а то я не знаю как это делать

**Comment by ElizarovEugene** [comment]
зайдите по ssh на свой сервер, перейдите в директорию ТМ, запустите - php -q engine.php

**Comment by c4uran** [comment]
Royal Pains на трекере newstudio.tv 
<br />castle 7 на трекере nnm-club.me 
<br />Неизвестный на трекере nnm-club.me 
<br />Royal Pains 7 на трекере rutor.org 
<br />Опрос новых раздач пользователей на трекерах: 
<br />================== 
<br />Выполение служебных функций: 
<br />Добавляем темы из Temp. 
<br />Обновление новостей. 
<br />Запись времени последнего запуска ТМ. 
<br />

**Comment by c4uran** [comment]
nnm заработал rutor так же

**Comment by ElizarovEugene** [comment]
проблем не наблюдаю
https://monosnap.com/file/nBt3lnMlJh0Jltus9r90QNFEKeMV7k

**Comment by c4uran** [comment]
это может быть связанно с блокировкой rutor? там через зеркало нужно ссылки добавлять, нет?

**Comment by ElizarovEugene** [comment]
Да, рутор работает через зеркало http://cool-tor.org

**Comment by c4uran** [comment]
не помогло :( ладно в пень рутор буду через ннм

**Comment by c4uran** [comment]
Кстати понял в чем дело перечитав гайд, дело ведь было в том что до тех пор пока человек не изучит как работает рсс лента кажется что монитор не работает

В хелпе к монитору написано: "TM просматривает ленту и ищет совпадения. ТМ не умеет выкачивать старые серии" - это правда, но для понимания не указанно на сколько старые, т.е если трекер за 1 день выкладывает 15 новых серий (а у тебя обновление листа раз в пару дней) то крайне вероятно что нужная серия найдена не будет. (хотя старой она будет только для rss ленты а не по времени)

можете чуть подробнее описать этот процесс в хелпе, хотя разобравшись один раз становится понятно уже совсем (пока сам не поковырялся с другими прогами не разобрался)
