### ISSUE TITLE
Не работает на Ubuntu 15.10

### ISSUE THREAD

**Issue by gelato** [ElizarovEugene/TorrentMonitor#190]
Собственно не могу понять почему не работает, чтобы исправить - логи не достаточно подробны.
При этом rutracker rutor и baibako сообщают -  Не могу получить доступ к трекеру.
Работало у меня с демоном deluged - сейчас даже не пытается что-то выкачать.
Как отдебажить и исправить?

**Comment by ElizarovEugene** [comment]
У нас все обсуждения вот сюда переехали
http://korphome.ru/TorrentMonitor/

Ну и нужно больше подробностей - как давно не работает? Новая установка? Апдейты? Что с PHP и БД на сервере? Что в показывает при включении дебага?
