### ISSUE TITLE
1.2.9 перестал работать запуск

### ISSUE THREAD

**Issue by c4uran** [ElizarovEugene/TorrentMonitor#191]
Сегодня днем обновил клиент под synology 

В результате когда нажимаю на Запуск начинает крутиться анимация загрузки и всё 

Последний запуск: 18 Янв 2016 16:30:43

проверку проходит: 
Подключение к интернету установлено.
Конфигурационный файл существует и заполнен.
Расширение cURL установлено.
Запись в директорию для torrent-файлов /volume1/web/torrentmonitor/torrents/ разрешена.
Запись в системную директорию /volume1/web/torrentmonitor/ разрешена.

Вот что вываливает ssh:
php -q engine.php
PHP Fatal error:  Call to undefined method Sys::checkConfig() in /volume1/web/torrentmonitor/engine.php on line 16

**Comment by ElizarovEugene** [comment]
http://korphome.ru/TorrentMonitor/viewtopic.php?f=6&t=121#p963

**Comment by c4uran** [comment]
Всё работает, спасибо!
