### ISSUE TITLE
Поблема с темой содержашей символ  ' (апостроф)

### ISSUE THREAD

**Issue by wrkit** [ElizarovEugene/TorrentMonitor#192]
Словил глюк. 
Тема в названии содержала апостроф  "Childhood's End" 
Из за апострофа разьехалась разметка блока таблицы на кнопке удалить в функции 
onclick="del()", и соответственно кнопка  перестала работать.
пришлось переименовывать тему (убрав символ), и потом удалять.
Не критично, но не все сообразят, может кодировать текст urldecode, на случай апострофов.

**Comment by ElizarovEugene** [comment]
Спасибо, подумаю
