### ISSUE TITLE
Перестал работать nnm

### ISSUE THREAD

**Issue by c4uran** [ElizarovEugene/TorrentMonitor#193]
версия TorrentMonitor v. 1.3.1
Последняя вываленая ошибка была:

> 24 Мар 2016 11:30    nnm-club.me     Не могу получить доступ к трекеру.

при этом **проверку проходит**

> Основной файл для работы с трекером nnmclub.to найден.
> Учётные данные для работы с трекером nnmclub.to найдены.
> Трекер nnmclub.to доступен.

Через браузер если пытаюсь зайти на **nnm-club.me** вываливает такую ошибку:

> Не удается получить доступ к сайту
> Не удается найти DNS address сервера nnm-club.me.

**nnmclub.to** открывается браузером нормально

сейчас ошибок не вываливает но торрент не скачивается
у меня одного такая проблема?

**Comment by c4uran** [comment]
UPD:

php -q /volume1/web/torrentmonitor/engine.php

вываливает:
PHP Fatal error:  Undefined class constant 'MYSQL_ATTR_INIT_COMMAND' in /volume1/web/torrentmonitor/class/Database.class.php on line 20

Fatal error: Undefined class constant 'MYSQL_ATTR_INIT_COMMAND' in /volume1/web/torrentmonitor/class/Database.class.php on line 20

**Comment by ElizarovEugene** [comment]
Добрый. Вы б на форум приходили, я тут и не бываю
По поводу ннм: судя по всему у вас не применилось обновление mysql и в раздачах остался nnm-club.me, а не mmnclub.ru
По поводу базы: переустанавливали/обновляли что то? у вас поддержка pdo-mysql отвалилась в php

**Comment by c4uran** [comment]
все висит на synology, вышло крупное обновление DSM 6.0 - обновилось всё что было (откатить возможности нет, система закрыта в этом плане)

**Comment by ElizarovEugene** [comment]
заходите на форум, там как раз владельцы сины делятся своими проблемами
