### ISSUE TITLE
lostfilm.tv, TM 1.4.1 - пытается добавить в Transmission все торренты с одним именем файла

### ISSUE THREAD

**Issue by sergey-s-betke** [ElizarovEugene/TorrentMonitor#194]
Большое спасибо за приложение! Облегчает отдых...

Добавил на мониторинг 5 сериалов c lostfilm.tv. Нажал "запуск" (установлен как аддон на DNS-325). В результате - загрузился и успешно запустился только один торрент - Grimm, последняя доступная серия. Все остальные торренты TM пытается добавить в transmission **с тем же именем файла** (что и у последней серии Grimm), на чём и падает - Transmission отказывает, говорит "такой торрент уже есть и работает".

**Comment by sergey-s-betke** [comment]
Сейчас результат такой:

Опрос новых раздач на трекерах: 
Elementary на трекере lostfilm.tv 
grimm на трекере lostfilm.tv 
Marvel's Agents of S.H.I.E.L.D. на трекере lostfilm.tv 
sherlock на трекере lostfilm.tv 
The Expanse на трекере lostfilm.tv 
The Night Manager на трекере lostfilm.tv 
Опрос новых раздач пользователей на трекерах: 
================== 
Выполение служебных функций: 
Добавляем темы из Temp. 

Fatal error: Allowed memory size of 67108864 bytes exhausted (tried to allocate 39 bytes) in /mnt/HD/HD_a2/Nas_Prog/torrentmonitor/php/class/Database.class.php on line 1009

причина - в temp накапливаются  недобавленные серии в результате описанной ошибки при каждом запуске...

**Comment by ElizarovEugene** [comment]
Здравствуйте
1. Давайте перенесём дискуссию на наш форум http://korphome.ru/TorrentMonitor/viewforum.php?f=4
2. Мне требуется больше информации http://korphome.ru/TorrentMonitor/viewtopic.php?f=4&t=112
3. Я не очень понял вашу формулировку "пытается добавить в transmission с тем же именем файла" - если можно - скриншотами из консоли/базы/etc.
