### ISSUE TITLE
Загрузка с lostfilm

### ISSUE THREAD

**Issue by gelato** [ElizarovEugene/TorrentMonitor#200]
Добрый вечер.
Внезапно прекратилась загрузка торрентов с lostfilm... Да еще и форум у вас упал...

**Comment by ElizarovEugene** [comment]
Добрый вечер.
Закачка вроде работает
Transmission, [29.01.18 19:00]
Трекер:  lostfilm.tv
Сообщение:  Blindspot HD обновлён до 11 серии, 3 сезона. И добавлен в torrent-клиент.

Да и форум так же работает, просто у него адрес изменился
http://forum.korphome.ru/

**Comment by gelato** [comment]
Тогда я ничего не понимаю - с newstudio качает, с лоста - нет.
Чтобы не быть паникером на пустом месте - грохнул все, перекачал torrent monitor, грохнул базу, восстановил бэкап - ничего, все то же самое. А началось все с того, что какого-то лешего слетели данные авторизации лоста, а с ними и все мониторящиеся сериалы.

Вывод такой:

`Опрос новых раздач на трекерах:
Ghost Wars на трекере baibako.tv

cant_find_rss
Время выполнения: 1.1030440330505
No Tomorrow на трекере baibako.tv
Время выполнения: 3.4093856811523E-5
Orphan Black на трекере baibako.tv
Время выполнения: 3.0994415283203E-5
Agents of S.H.I.E.L.D. на трекере lostfilm.tv

captcha
Время выполнения: 0.63378095626831
Altered Carbon на трекере lostfilm.tv
Время выполнения: 0.61389207839966
American Crime Story на трекере lostfilm.tv
Время выполнения: 0.64473104476929
American Gods на трекере lostfilm.tv
Время выполнения: 0.66180396080017
American Horror Story на трекере lostfilm.tv
Время выполнения: 0.65272307395935
A Series of Unfortunate Events на трекере lostfilm.tv
Время выполнения: 0.63884496688843
Black Lightning на трекере lostfilm.tv
Время выполнения: 0.65816617012024
Black Mirror на трекере lostfilm.tv
Время выполнения: 0.64449286460876
Counterpart на трекере lostfilm.tv
Время выполнения: 0.65383791923523
Daredevil на трекере lostfilm.tv
Время выполнения: 0.65556597709656
Elementary на трекере lostfilm.tv
Время выполнения: 0.6493558883667
Game of Thrones на трекере lostfilm.tv
Время выполнения: 0.64733195304871
Ghosted на трекере lostfilm.tv
Время выполнения: 0.64852404594421
Happy! на трекере lostfilm.tv
Время выполнения: 0.63979387283325
Hawaii Five-0 на трекере lostfilm.tv
Время выполнения: 0.6612651348114
Iron Fist на трекере lostfilm.tv
Время выполнения: 0.65148091316223
Jessica Jones на трекере lostfilm.tv
Время выполнения: 0.6537561416626
Killjoys на трекере lostfilm.tv
Время выполнения: 0.64439702033997
Lethal Weapon на трекере lostfilm.tv
Время выполнения: 0.66018080711365
Lucifer на трекере lostfilm.tv
Время выполнения: 0.62778615951538
Midnight, Texas на трекере lostfilm.tv
Время выполнения: 0.65054202079773
Mindhunter на трекере lostfilm.tv
Время выполнения: 0.66246891021729
Modern Family на трекере lostfilm.tv
Время выполнения: 0.65182399749756
Mr. Mercedes на трекере lostfilm.tv
Время выполнения: 0.64419102668762
Mr. Robot на трекере lostfilm.tv
Время выполнения: 0.63836002349854
Philip K. Dick's Electric Dreams на трекере lostfilm.tv
Время выполнения: 0.65570092201233
Preacher на трекере lostfilm.tv
Время выполнения: 0.64054703712463
Scream на трекере lostfilm.tv
Время выполнения: 0.65459990501404
Stargate Origins на трекере lostfilm.tv
Время выполнения: 0.64102792739868
Star Trek: Discovery на трекере lostfilm.tv
Время выполнения: 0.65709900856018
Stranger Things на трекере lostfilm.tv
Время выполнения: 0.64673185348511
Supernatural на трекере lostfilm.tv
Время выполнения: 0.64725804328918
Taboo на трекере lostfilm.tv
Время выполнения: 0.6557559967041
The Alienist на трекере lostfilm.tv
Время выполнения: 0.64484190940857
The Flash на трекере lostfilm.tv
Время выполнения: 0.65234208106995
The Magicians на трекере lostfilm.tv
Время выполнения: 0.65854907035828
The Orville на трекере lostfilm.tv
Время выполнения: 0.637775182724
The X-Files на трекере lostfilm.tv
Время выполнения: 0.65205907821655
Timeless на трекере lostfilm.tv
Время выполнения: 0.64790678024292
American Horror Story на трекере newstudio.tv
Время выполнения: 0.69467401504517
Ash vs Evil Dead на трекере newstudio.tv
Время выполнения: 0.0097801685333252
Black Mirror на трекере newstudio.tv
Время выполнения: 0.0097110271453857
Brooklyn Nine-Nine на трекере newstudio.tv
Время выполнения: 0.0081260204315186
Bull на трекере newstudio.tv
Время выполнения: 0.0099208354949951
Scream Queens на трекере newstudio.tv
Время выполнения: 0.0081989765167236
Supernatural на трекере newstudio.tv
Время выполнения: 0.0087769031524658
The Grand Tour на трекере newstudio.tv
Время выполнения: 0.0098249912261963
Young Sheldon на трекере newstudio.tv
Время выполнения: 0.0098810195922852
Star vs Evil Forces на трекере rutracker.org
Время выполнения: 0.76468801498413
The Big Bang Theory на трекере rutracker.org
Время выполнения: 0.74641084671021
TrollHunters на трекере rutracker.org
Время выполнения: 0.73139905929565
Общее время опроса трекеров: 30.226437091827
Опрос новых раздач пользователей на трекерах:
Общее время опроса пользователей на трекерах: 9.5367431640625E-7
==================
Выполение служебных функций:
Добавляем темы из Temp.
Время выполнения: 0.0010459423065186
Обновление новостей.
Время выполнения: 0.42820405960083
Удаление старых torrent-файлов.
Установка обновлений.
Текущая версия системы: 1.7.4
Текущая версия базы данных: 1.7.4
Текущая версия системы является актуальной.
Запись времени последнего запуска ТМ.
Общее время работы скрипта: 30.868429899216 `

**Comment by ElizarovEugene** [comment]
Вот у вас верно крупный шрифт начался, в нужном месте - captcha
Если открыть страницу ошибок в ТМ, там должна быть запись: "При авторизации запрашивается капча. Необходимо остановить ТМ на 2-3 часа."

Можно поступить иначе - зайти на лост, разлогиниться, залогиниться введя капчу, после этого она обычно при следующем логине уже не запрашивается.
Ну а предварительно проверить что учётка правильная в ТМ забита

**Comment by gelato** [comment]
При перелогине не запрашивается капча... Но я его остановлю, спасибо. Насчет ошибок - у меня там набралось их оказывается 35 тыс. штук за годы пользования, и на той страничке ничего не отображалось (страница с ошибками у меня за все время пользования корректно всего пару раз работала) сейчас почистил табличку, может заработает как надо.
Спасибо.

**Comment by ElizarovEugene** [comment]
```При перелогине не запрашивается капча...```
да, это сработает, если у вас тот же внешний IP что и у ТМ...

**Comment by gelato** [comment]
Вчера пробовал, но тоже капчу не просило. Бог с ним - приду домой, попробую с домашнего адреса еще раз перелогиниться. Лосты что-то совсем невзлюбили автоматизацию...

**Comment by gelato** [comment]
А вообще кстати было бы круто пробрасывать капчу пользователю torrent monitor-a, ну и уведомлять об этом в телеграме. Ну так, просто идея на будущее )

**Comment by ElizarovEugene** [comment]
Так вы включите уведомления об ошибках, он будет вам в телеграм присылать сообщение
http://take.ms/cm6nO
А проброс капчи не знаю как решит проблему, это тогда надо что бы ТМ сессию не завершал, пока пользователь не ответит, а если не ответит? так и будет висеть. а при следующем логине она уже новая

**Comment by gelato** [comment]
Ну, сессию открытой можно держать например час. И переключалку поставть - вкл/выкл функционал. Ну так, в порядке бреда - почему нет. По кайфу конечно было бы кидать в телеграм-бота капчей, и ждать от юзера ввода.
А уведомления об ошибках включил только что ))
