### ISSUE TITLE
cant_find_cookie

### ISSUE THREAD

**Issue by Vozdr** [ElizarovEugene/TorrentMonitor#202]
Доброго дня!
Перестал подтягивать обновления с lostfilm. При запуске пишет cant_find_cookie, в ошибках:
27 Дек 2019 06:53 | lostfilm.tv | Не удалось найти куки.

Пробовал пересоздать контейнер - эффект тот же

**Comment by ElizarovEugene** [comment]
На прошлой неделе лост заблокировали, вероятнее всего дело в этом

**Comment by ElizarovEugene** [comment]
Лучше приходите в наш телеграм чат
https://t.me/joinchat/DFRbKQvV_FQA8TatJjlWRw
