### ISSUE TITLE
Portainer

### ISSUE THREAD

**Issue by liklaysh** [ElizarovEugene/TorrentMonitor#204]
Как вариант для модернизации продукта! 
Добавить возможность делать развертку через Portainer цены бы вам не было, для многих кто сейчас работает с контейнерами делать развертку через Stacks в Portainer намного удобнее.
Так как сейчас популярные такие темы как nas4free и openmediavault для домашних систем.
Удачи в развитии!

**Comment by snowymanul** [comment]
разворачивйте через docker-compose, кто ж вам мешает,  ссылка на  docker-hub  в описании.  Stacks в Portainer это и есть композ файлы...
