### ISSUE TITLE
Добавлять заголовки в RSS feed

### ISSUE THREAD

**Issue by e1fueg0** [ElizarovEugene/TorrentMonitor#209]
Добрый день.

Вопрос такой: можно ли в rss добавлять внятные заголовки?
Например, я отслеживаю тему
заголовок: Библиотека Либрусек (lib.rus.ec) + MyHomeLib. [FB2] (Новый формат)
ссылка: http://booktracker.org/viewtopic.php?t=1198

в rss для торрента генерится такое:
```<item>
<title>2. [booktracker.org]_1198.torrent</title>
<pubDate>Tue, 11 Oct 2022 22:00:04 +0000</pubDate>
<link>http://192.168.91.9/torrents/[booktracker.org]_1198.torrent</link>
</item>
```

т.е., когда я получаю обновление фида в qbittorrent, мне надо идти в tormon, смотреть, что такое тема 1198, чтобы знать, какой торрент удалять и пересоздавать.

Или это можно делать как-то иначе, более по уму?

Спасибо.

**Comment by e1fueg0** [comment]
в докере стоит qbittorrent, конфиги и торренты лежат по симлинкам, прописанным на шару с НАСа, примонтированную по самбе
отдельно в докере стоит tormon. на его rss и настроен qbt.
наверное, можно было бы класть торренты в tormon в ту же шару, но по самбе слежение за директорией  не работает.

**Comment by e1fueg0** [comment]
но даже в такой ситуации не очень понятно, что будет с торрентами из тем, где раздача ведётся путём добавления новых серий. если есть новый торрент, то клиент же сам всё равно не удалит старый, в любом случае надо вручную добавлять. и тут опять-таки внятное имя помогло бы, чтобы знать, что удалять.

**Comment by e1fueg0** [comment]
Спасибо, нашёл, попробую.
Правда, не очень понятно из описания, что настройки делают.
>  Удалять раздачи из torrent-клиента

это, я так понимаю, удаляет старую раздачу, если есть новая. а оно нормально работает с категориями? в смысле, что qbittorrent кладёт раздачу в другой каталог, если категория задана.

>  Удалять файлы старых раздач
Только для lostfilm.tv, baibako.tv и newstudio.tv

а тут не очень понятно, зачем удалять файлы любых раздач.

**Comment by ElizarovEugene** [comment]
> qbittorrent кладёт раздачу в другой каталог, если категория задана
Категории не поддерживаются

> зачем удалять файлы любых раздач
Ну вот качаете вы по одной серии сериала с лоста и не хотите хранить их все, а только последнюю, по тому что смотрите её сразу и предыдущие уже не нужны

**Comment by e1fueg0** [comment]
понял, спасибо.
> Категории не поддерживаются

это не очень удобно.

**Comment by ElizarovEugene** [comment]
> кстати, а как вы определяете, что такая-то раздача -- это старая раздача для выкачанной новой?

хэш предыдущей хранится в БД

> это не очень удобно.

я думаю вопрос накладывания категорий или раскладывания по директория можно решить при помощи скриптов, которые можно запускать автоматически при обновлении раздачи. на самом деле редкий кейс
например https://pypi.org/project/python-qbittorrent/

**Comment by e1fueg0** [comment]
> хэш предыдущей хранится в БД

да, спасибо, я так и подумал.

> я думаю вопрос накладывания категорий или раскладывания по директория можно решить при помощи скриптов, которые можно запускать автоматически при обновлении раздачи. на самом деле редкий кейс например https://pypi.org/project/python-qbittorrent/

тут вопрос другой. к примеру, я сделал категорию "неполные", куда согнал все торренты, для которых версии будут добавляться. и все они, соответсвенно, лежат в `/downloads/неполные`. если я пропишу в настройках базовый каталог `/downloads`, то при пересоздании клиент просто не найдёт старые серии, и закачает всё заново (на самом деле не большая беда на анлиме =), но как-то тупо). если, с другой стороны, я пропишу `/downloads/неполные`, то как только я вручную или скриптом проставлю на торрент категорию, в лучшем случае я получу `/downloads/неполные/неполные/название сериала/серия01.mkv`, в худшем, если в коде кубита не предусмотрен такой вариант, все закачки из `/downloads/неполные` перенесутся в `/downloads/неполные/неполные/`, и все остальные будут перекачиваться. и мне как-то даже не хочется проверять, как оно будет =)

**Comment by ElizarovEugene** [comment]
Мне до конца не ясна задача на самом деле
Если задача сводится к тому, что какие-то раздачи нужно качать в определённый каталог, вы можете указать его не в глобальных настройках ТМ, а в настройках каждой раздачи и хоть каждый сериал качать в отдельную для него директорию.

**Comment by e1fueg0** [comment]
короче, в итоге написал для qbittorrent скрипт, который берёт торренты из каталога с торрентами вашего tormon, и отдаёт в клиент с учётом категорий и путей.

**Comment by e1fueg0** [comment]
Может, кому-то будет полезно
https://hub.docker.com/r/elfuego/torrent_sorter
