### ISSUE TITLE
Новые трекеры

### ISSUE THREAD

**Issue by sonicby** [ElizarovEugene/TorrentMonitor#5]
Хочется поддержки других трекеров.
http://free-torrents.org
http://book.libertorrent.com

**Comment by thefree** [comment]
Доброго дня.
Возможно добавить https://soap4.me/ ?

**Comment by ElizarovEugene** [comment]
@thefree здравствуйте. а что это за трекер? чьи там раздачи? чьи озвучки?

**Comment by maxus51** [comment]
Их собственные озвучки. Ребята хорошо переводят и озвучивают 

_____________________
Максим Юрьевич

**Comment by ElizarovEugene** [comment]
@maxus51 спасибо
тогда добавлю в тудулист и в выходные посмотрю на сколько  он "парсибелен" :)

**Comment by maxus51** [comment]
СПС. Будем ждать :) 

_____________________
Максим Юрьевич

**Comment by thefree** [comment]
@ElizarovEugene не уверин, что @maxus51 прав, это большой агрегатор сериалов с разных проектов озвучки.

**Comment by Ditinex-ru** [comment]
Добавьте https://www.anilibria.tv

**Comment by Free0wl** [comment]
очень хочется http://tapochek.net/
