### ISSUE TITLE
rutor.org

### ISSUE THREAD

**Issue by Leshtm** [ElizarovEugene/TorrentMonitor#96]
http://rutor.org/torrent/367767/
разный контент
http://new-rutor.org/torrent/367767/
или он медленно обновляется.

И rutor.org добавил проверку на javacript и cookies

**Comment by diff75** [comment]
http://alt.rutor.org/ видимо прилёг и проверка не работает

**Comment by ElizarovEugene** [comment]
@diff75 ну бывает
